---
sidebar: sidebar 
permalink: concept_about_applications.html 
keywords: applications, asset, cost 
summary: 会社の環境で使用されているアプリケーションを把握しておくと、アセットの使用状況やコストを追跡しやすくなります。 
---
= アプリケーションごとにアセットの使用状況を追跡する


[role="lead"]
会社の環境で使用されているアプリケーションを把握しておくと、アセットの使用状況やコストを追跡しやすくなります。

環境で実行されているアプリケーションに関連付けられているデータを追跡するには、まずそれらのアプリケーションを定義し、適切なアセットに関連付ける必要があります。アプリケーションを関連付けることができるアセットは、ホスト、仮想マシン、ボリューム、内部ボリューム、 qtree 、 共有、ハイパーバイザー：

ここでは、マーケティングチームが Exchange E メールに使用する仮想マシンの使用状況を追跡する例を示します。

環境で使用されているアプリケーションを特定し、各アプリケーションを使用してグループまたはビジネスユニットをメモするには、次のような表を作成します。

[cols="5*"]
|===


| テナント | 基幹業務部門 | ビジネスユニット | プロジェクト | アプリケーション 


| ネットアップ | データストレージ | 法律 | 特許 | Oracle Identity Manager 、 Oracle On Demand 、 PatentBuy 


| ネットアップ | データストレージ | マーケティング | セールスイベント | Exchange 、 Oracle 共有データベース、 BlastOff Event Planner 
|===
次の表は、マーケティングチームが Exchange アプリケーションを使用していることを示しています。ストレージの追加がいつ必要になるかを予測できるように、 Exchange の仮想マシンの使用率を追跡したいと考えています。Exchange アプリケーションをマーケティング部門のすべての仮想マシンに関連付けることができます。

. Exchange という名前のアプリケーションを作成します
. [ クエリ ] 、 [ 新規クエリ ] の順に移動して、仮想マシンの新しいクエリを作成します ( 必要に応じて、既存の VM クエリを選択します ) 。
+
マーケティングチームの VM のすべてに文字列「 * mkt * 」を含む名前があると仮定して、「 mkt 」の VM 名をフィルタリングするクエリを作成します。

. VM を選択します。
. *Bulk Actions > Add Applications * を使用して、 VM を _Exchange_application に関連付けます。
. 目的のアプリケーションを選択し、 * 保存 * をクリックします。
. 完了したら、 * クエリを保存 * します。

