---
sidebar: sidebar 
permalink: concept_asset_user_data_section.html 
summary: アセットページの User Data セクションでは、アノテーションやアプリケーションを現在のアセットに割り当てることができます。 
keywords: asset page, user data, applications, annotations 
---
= User Data セクション
:allow-uri-read: 


[role="lead"]
アセットページの User Data セクションには、アプリケーションやアノテーションなどのユーザ定義データが表示されます。データの変更も可能です。



== User Data セクションを使用してアプリケーションを割り当てまたは変更する

環境で実行しているアプリケーションを特定のアセット（ホスト、仮想マシン、ボリューム、内部ボリューム、 qtree 、 ハイパーバイザーを含む）。User Data セクションでは、アセットに割り当てられているアプリケーションを追加、変更、または削除できます。これらのアセットタイプにボリュームを除くすべてのタイプを対象に、複数のアプリケーションを割り当てることができます。

.手順
. 次のいずれかの方法でアセットページを検索します。
+
.. アセットのリストを照会し、リストから 1 つ選択します。
.. ダッシュボードで、アセット名を確認してクリックします。
.. 検索を実行し、結果からアセットを選択します。
+
アセットページが表示されます。ページの User Data セクションには、現在割り当てられているアプリケーションまたはアノテーションが表示されます。





割り当てられているアプリケーションを変更したり、アプリケーションやその他のアプリケーションを割り当てるには、 * Application * リストをドロップダウンして、アセットに割り当てるアプリケーションを選択します。アプリケーションを検索するにはを入力し、リストからアプリケーションを選択します。

アプリケーションを削除するには、アプリケーションリストをドロップダウンし、アプリケーションのチェックを解除します。



== User Data セクションを使用して、注釈を割り当てまたは変更する

Cloud Insights をカスタマイズして会社の要件に合わせてデータを追跡するときは、アノテーションと呼ばれる特殊な注釈を定義してアセットに割り当てることができます。アセットページの User Data セクションには、アセットに割り当てられているアノテーションが表示されます。また、そのアセットに割り当てるアノテーションを変更することもできます。

.手順
. アセットにアノテーションを追加するには、アセットページの User Data セクションで、 * + Annotation * をクリックします。
. リストからアノテーションを選択します。
. 値をクリックし、選択したアノテーションのタイプに応じて次のいずれかを実行します。
+
.. アノテーションタイプがリスト、日付、またはブーリアンの場合は、値をリストから選択します。
.. アノテーションタイプがテキストの場合は、値を入力します。


. [ 保存 ] をクリックします .


アセットにアノテーションが割り当てられ、クエリでアノテーションに基づいてアセットをフィルタできるようになります。

アノテーションを割り当てたあとに値を変更する場合は、アノテーションリストをドロップダウンして別の値を入力します。

fly_option で新しい値を追加するために _Add を選択したリストタイプのアノテーションの場合は ' 既存の値を選択するだけでなく ' 新しい値を追加することもできます
