---
sidebar: sidebar 
permalink: concept_forensic.html 
keywords: Forensic, user, entity, community 
summary: フォレンジックの概要 
---
= フォレンジック情報
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:history: Review 1/17,
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
フォレンジックビューは、ユーザー、エンティティ、コミュニティ、ユーザーアクティビティ情報へのアクセスを提供します。



== ユーザ情報の確認

［ * Forensic （フォレンジック） ］ > ［ User （ユーザー） ］ をクリックして、ユーザービューにアクセス

このビューには、一般的なユーザ情報が表示されます

* ユーザの名前。ユーザの詳細情報へのリンクが表示されます。
* ユーザのアクティビティによって生成されたアラート
* ユーザが属しているコミュニティの数。コミュニティページへのリンクがあります
* ユーザの場所
* ユーザーが最後にアクセスしたエンティティ


ユーザ名をクリックすると、で詳細情報にアクセスできます link:forensic_user_detail.html["ユーザーの概要"]



== エンティティ情報の検査

Forensics > Entity * をクリックして、 Entity ビューにアクセスします。

このページには、ユーザがアクセスしているエンティティの一般的な情報が表示されます。

以下の詳細について説明します。

* エンティティ名
* エンティティタイプ


* エンティティとのコミュニティ関係
* エンティティパス
* 最終アクセス日時
* エンティティサイズ


エンティティ名（ Entity Name ）をクリックして、で詳細な情報にアクセスします link:forensic_entity_detail.html["エンティティの概要（ Entity Overview"]

コミュニティ数をクリックすると、エンティティを含むコミュニティが表示されます。



== コミュニティ情報の調査

[*Forensic] > [Communities*] をクリックして、 [Communities] ページにアクセスします。

このビューには次の機能があり

* コミュニティ名
* コミュニティに関連するアラート
* コミュニティのユーザ数
* コミュニティのエンティティ数


コミュニティ名をクリックまたは検索して、コミュニティの詳細ページにアクセスします。

コミュニティプロファイル:: コミュニティユーザの場所およびその他の最も近いコミュニティをリストします。
コミュニティビヘイビア:: アクセスされたエンティティの数と、読み取り、書き込み、およびメタデータアクセスの処理を示します。
ユーザーとエンティティ（ User and Entities ）:: コミュニティ内の合計ユーザ数と合計エンティティ数を示します。
コミュニティ分析::
+
--
* コミュニティユーザの傾向
* エンティティに対して実行される操作
* アラートの傾向


--


コミュニティ名をクリックすると、で詳細情報にアクセスできます link:forensic_community_detail.html["コミュニティの詳細"]



== ユーザアクティビティ情報の確認

［ * Forensics （フォレンジック） ］ > ［ User Activity （ユーザーアクティビティ） ］ をクリックして、 ［ User Activity （ユーザーアクティビティ） ］

このビューには、監視対象の各ユーザについて次の情報が表示されます。

* エンティティのアクセス時間
* ユーザー概要へのリンクを持つエンティティにアクセスしたユーザー
* 実施されたアクティビティ：
+
** 読み取り
** 書き込み
** 作成
** 名前を変更する


* エンティティパス
* エンティティタイプ
* アクセスの場所ユーザ名をクリックすると、で詳細情報にアクセスできます link:forensic_user_detail.html["エンティティの詳細"]

