---
sidebar: sidebar 
permalink: concept-client-protocols.html 
keywords: client protocols, client version, smb version, nfs version, protocol versions, s3, smb, nfs, iscsi, cifs 
summary: Cloud Volumes ONTAP は、iSCSI、NFS、SMB、NVMe-TCP、およびS3クライアントプロトコルをサポートします。 
---
= クライアントプロトコル
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP は、iSCSI、NFS、SMB、NVMe-TCP、およびS3クライアントプロトコルをサポートします。



== iSCSI

iSCSI は、標準のイーサネットネットワークで実行できるブロックプロトコルです。ほとんどのクライアントオペレーティングシステムには、標準のイーサネットポートで動作するソフトウェアイニシエータが搭載されています。



== NFS

NFS は、 UNIX および Linux システム向けの従来のファイルアクセスプロトコルです。クライアントは、 NFSv3 、 NFSv4 、および NFSv4.1 プロトコルを使用して ONTAP ボリューム内のファイルにアクセスできます。ファイルアクセスは、 UNIX 形式の権限、 NTFS 形式の権限、またはその両方の組み合わせを使用して制御できます。

クライアントは、 NFS プロトコルと SMB プロトコルの両方を使用して同じファイルにアクセスできます。



== SMB

SMB は、 Windows システム向けの従来のファイルアクセスプロトコルです。クライアントは、 SMB 2.0 、 SMB 2.1 、 SMB 3.0 、および SMB 3.1.1 の各プロトコルを使用して ONTAP ボリューム内のファイルにアクセスできます。NFS と同様に、複数の形式の権限の組み合わせがサポートされています。



== S3

Cloud Volumes ONTAP は、スケールアウトストレージ用のオプションとしてS3をサポートしています。S3プロトコルをサポートすることで、Storage VM（SVM）のバケットに格納されたオブジェクトへのS3クライアントアクセスを設定できます。

link:https://docs.netapp.com/us-en/ontap/s3-multiprotocol/index.html#how-s3-multiprotocol-works["S3マルチプロトコルの仕組みを説明します"^]。
link:https://docs.netapp.com/us-en/ontap/object-storage-management/index.html["ONTAP で S3 オブジェクトストレージサービスを設定および管理する方法について説明します"^]。



== nvme-tcpが表示されます

Cloud Volumes ONTAP バージョン9.12.1以降を使用している場合、クラウドプロバイダではnvme-tcpがサポートされます。BlueXPには、NVMe-oF TCPの管理機能はありません。

ONTAP を使用したNVMeの設定の詳細については、を参照してください https://docs.netapp.com/us-en/ontap/san-admin/configure-svm-nvme-task.html["NVMe用のStorage VMを設定する"^]。
