---
sidebar: sidebar 
permalink: concept_cs_api.html 
keywords: api, access, token, swagger 
summary: Cloud Secure には、 CMDB などの他のアプリケーションと統合するための強力な API が用意されています。 
---
= Cloud Secure API の略


[role="lead"]
Cloud Secure API を使用すると、ネットアップのお客様と独立系ソフトウェアベンダー（ ISV ）は、 Cloud Secure を CMDB や他のチケット発行システムなどの他のアプリケーションと統合できます。

API アクセスの要件：

* API アクセストークンモデルを使用してアクセスが許可されます。
* API トークン管理は、管理者ロールを持つ Cloud Secure ユーザが実行します。




== API ドキュメント（ Swagger ）

最新の API 情報は、 Cloud Secure にログインし、 * Admin > API Access * に移動することで確認できます。[API Documentation*] リンクをクリックします。API ドキュメントは Swagger ベースです。 API の簡単な概要情報と使用方法を提供しており、環境内で試すことができます。



== API アクセストークン

Cloud Secure API を使用する前に、 1 つ以上の * API アクセストークン * を作成する必要があります。アクセストークンは読み取り権限を付与します。各アクセストークンの有効期限を設定することもできます。

アクセストークンを作成するには：

* [*Admin] > [API Access*] をクリックします
* [*+API アクセストークン *] をクリックします
* 「 * トークン名 * 」と入力します
* トークンの有効期限 * を指定します



NOTE: トークンは、クリップボードにコピーして作成プロセス中に保存する場合にのみ使用できます。トークンは作成後に取得できないため、トークンをコピーして安全な場所に保存することを強くお勧めします。トークンの作成画面を閉じる前に、 [API アクセストークンのコピー ] ボタンをクリックするよう求められます。

トークンを無効化、有効化、および取り消しできます。無効になっているトークンを有効にできます。

トークンを使用すると、お客様の観点から API への汎用アクセスが許可され、環境の範囲内で API へのアクセスが管理されます。

アプリケーションは、ユーザがアクセスの認証と許可に成功した後、ターゲット API を呼び出すときにアクセストークンをクレデンシャルとして渡します。渡されたトークンは、トークンのベアラに対して API へのアクセスが許可されていることを API に通知し、許可中に付与されたスコープに基づいて特定のアクションを実行します。

アクセストークンが渡される HTTP ヘッダーは * X-CloudInsights - apiKey ： * です

たとえば、次のようにしてストレージアセットを取得します。

 curl https://<tenant_host_name>/rest/v1/cloudsecure/activities -H 'X-CloudInsights-ApiKey: <API_Access_Token>'
_<API_Access_Token> _ は、 API アクセスキーの作成時に保存したトークンです。

詳細については、 _API Documentation_link の * Admin > API Access * を参照してください。
