---
sidebar: sidebar 
permalink: concept-storage-management.html 
keywords: provisioning, capacity management, storage provisioning, manual, automatic, advanced allocation, aggregates, thin provisioning, free space, mode, BlueXP, cloud manager 
summary: BlueXPでは、Cloud Volumes ONTAP ストレージをシンプルかつ高度に管理できます。 
---
= ストレージ管理
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXPでは、Cloud Volumes ONTAP ストレージをシンプルかつ高度に管理できます。


CAUTION: すべてのディスクとアグリゲートは、BlueXPから直接作成および削除する必要があります。これらのアクションは、別の管理ツールから実行しないでください。これにより、システムの安定性が低下し、将来ディスクを追加できなくなる可能性があります。また、クラウドプロバイダの冗長料金が発生する可能性もあります。



== ストレージのプロビジョニング

BlueXPを使用すると、ディスクを購入してアグリゲートを管理することで、Cloud Volumes ONTAP 用のストレージのプロビジョニングを簡単に行うことができます。ボリュームを作成するだけで済みます。必要に応じて、 Advanced Allocation オプションを使用してアグリゲートをプロビジョニングできます。



=== プロビジョニングの簡素化

アグリゲートは、ボリュームにクラウドストレージを提供します。BlueXPでは、インスタンスを起動するとき、および追加のボリュームをプロビジョニングするときにアグリゲートが作成されます。

ボリュームを作成すると、BlueXPは次の3つのうちいずれかの処理を行います。

* 十分な空きスペースがある既存のアグリゲートにボリュームを配置します。
* ボリュームを既存のアグリゲートに配置するには、そのアグリゲート用に追加のディスクを購入します。


ifdef::aws[]

[+]
Elastic VolumesをサポートするAWSのアグリゲートの場合は、BlueXPでRAIDグループ内のディスクのサイズも拡張されます。 link:concept-aws-elastic-volumes.html["Elastic Volumesのサポートに関する詳細情報"]。

endif::aws[]

* 新しいアグリゲートのディスクを購入し、そのアグリゲートにボリュームを配置します。


BlueXPでは、アグリゲートの最大サイズ、シンプロビジョニングが有効かどうか、アグリゲートの空きスペースのしきい値など、いくつかの要因によって新しいボリュームをどこに配置するかを決定します。


TIP: アカウント管理者は、 [ 設定 *] ページから空き容量のしきい値を変更できます。

ifdef::aws[]



==== AWS でのアグリゲートのディスクサイズの選択

Cloud Volumes ONTAP 用の新しいアグリゲートをAWSで作成すると、システムのアグリゲートの数が増えるにつれて、アグリゲートのディスクサイズが徐々に拡張されます。BlueXPは、AWSが許容する最大データディスク数に達する前に、システムの最大容量を利用できるようにします。

たとえば、BlueXPでは、次のようなディスクサイズが選択される場合があります。

[cols="3*"]
|===
| アグリゲート番号 | ディスクサイズ | 最大アグリゲート容量 


| 1. | 500GiB | 3TiB 


| 4. | 1TiB | 6TiB 


| 6. | 2TiB | 12TiB 
|===

NOTE: この動作は、Amazon EBS Elastic Volumes機能をサポートするアグリゲートには適用されません。Elastic Volumesが有効になっているアグリゲートは、1つまたは2つのRAIDグループで構成されます。各RAIDグループには、同じ容量の同一ディスクが4本あります。 link:concept-aws-elastic-volumes.html["Elastic Volumesのサポートに関する詳細情報"]。

ディスクサイズは、 Advanced Allocation オプションを使用して選択できます。

endif::aws[]



=== 高度な割り当て

BlueXPでは、アグリゲートを自分で管理する代わりに、自分で管理できます。 link:task-create-aggregates.html["Advanced allocation * ページからアクセスします"]では、特定の数のディスクを含む新しいアグリゲートの作成、既存のアグリゲートへのディスクの追加、および特定のアグリゲートでのボリュームの作成を行うことができます。



== 容量管理

アカウント管理者は、BlueXPがストレージ容量の決定を通知するかどうか、またはBlueXPが容量の要件を自動的に管理するかどうかを選択できます。

この動作は、コネクタの_Capacity Management Mode_onによって決定されます。容量管理モードは、そのコネクタで管理されているすべてのCloud Volumes ONTAP システムに影響します。別のコネクタがある場合は、別の方法で設定できます。



=== 自動容量管理

容量管理モードは、デフォルトで自動に設定されています。このモードでは、Cloud Volumes ONTAP インスタンスで追加の容量が必要になると、自動的に新しいディスクが購入されます。また、未使用のディスクセット（アグリゲート）の削除、必要に応じてアグリゲート間でのボリュームの移動、ディスクの障害状態の解除などを実行します。

次の例は、このモードの動作を示しています。

* アグリゲートの容量がしきい値に達し、ディスクの容量が増えても、BlueXPはそのアグリゲート用の新しいディスクを自動的に購入するため、ボリュームを継続して拡張することができます。
+
BlueXPは15分ごとに空き容量の比率をチェックし'追加のディスクを購入する必要があるかどうかを判断します



ifdef::aws[]

[+]
Elastic VolumesをサポートするAWSのアグリゲートの場合は、BlueXPでRAIDグループ内のディスクのサイズも拡張されます。 link:concept-aws-elastic-volumes.html["Elastic Volumesのサポートに関する詳細情報"]。

endif::aws[]

* アグリゲートが容量のしきい値に達し、かつ他のディスクをサポートできない場合は、使用可能な容量を持つアグリゲートまたは新しいアグリゲートにボリュームが自動的に移動されます。
+
ボリュームに新しいアグリゲートを作成すると、そのボリュームのサイズに対応するディスクサイズが選択されます。

+
元のアグリゲートに空きスペースがあることに注意してください。既存のボリュームまたは新しいボリュームでは、そのスペースを使用できます。このシナリオでは、スペースをクラウドプロバンスに戻すことはできません。

* アグリゲートにボリュームが12時間以上格納されていない場合、BlueXPはそのアグリゲートを削除します。




==== 容量の自動管理による LUN の管理

BlueXPの自動容量管理はLUNには適用されませんBlueXPでLUNを作成すると'自動拡張機能が無効になります



=== 手動による容量管理

アカウント管理者が容量管理モードを手動に設定した場合、容量の決定が必要になったときに「Action Required」メッセージが表示されます。自動モードで説明されている例と同じ例が手動モードにも適用されますが、アクションを受け入れる必要があります。



=== 詳細はこちら。

link:task-manage-capacity-settings.html["容量管理モードを変更する方法について説明します"]。
