---
sidebar: sidebar 
permalink: concept_asset_page_overview.html 
summary: アセットページは、ほとんどのオブジェクトタイプについて表示できます。 
keywords: asset page, objects, landing page, Virtual machine, VM, Storage Virtual Machine, SVM, Volume, Internal volume, Host, Hypervisor, pool, Storage, Datastore, Application, node, Qtree, Disk, VMDK, Port, Switch, Fabric 
---
= アセットページの概要


[role="lead"]
アセットページには、アセットの現在のステータスの概要と、アセットと関連するアセットに関する追加情報へのリンクが表示されます。



== アセットページのタイプ

Cloud Insights には、次のアセットのアセットページがあります。

* 仮想マシン
* Storage Virtual Machine （ SVM ）
* ボリューム
* 内部ボリューム
* ホスト（ハイパーバイザーを含む）
* ストレージプール
* ストレージ
* データストア
* アプリケーション
* ストレージノード
* qtree
* ディスク
* VMDK です
* ポート
* スイッチ
* ファブリック




== 表示データの時間範囲を変更する

アセットページにはデフォルトでは過去 24 時間のデータが表示されますが、他の一定の期間やカスタムの期間を選択して、その範囲のデータを表示することができます。

アセットの種類に関係なく、すべてのアセットページに表示されるオプションを使用して、データを表示する期間を変更することができます。時間範囲を変更するには、トップバーに表示されている時間範囲をクリックし、次の時間セグメントから選択します。

* 最後の 15 分
* 過去 30 分
* 過去 60 分
* 過去 2 時間
* 過去 3 時間（デフォルト）
* 過去 6 時間
* 過去 12 時間
* 過去 24 時間
* 過去 2 日間
* 過去 3 日間
* 過去 7 日間
* 過去 30 日間
* カスタムの期間


カスタム期間では、最大 31 日間連続で選択できます。この範囲に開始時間と終了時間を設定することもできます。デフォルトの開始時間は、最初に選択した日の午前 12 時、最後に選択した日のデフォルトの終了時間は午後 11 時 59 分です。適用をクリックすると、カスタムの期間がアセットページに適用されます。



== カスタムウィジェットを追加します

任意のアセットページに独自のウィジェットを追加できます。追加したウィジェットは、そのタイプのすべてのオブジェクトのアセットページに表示されます。たとえば、ストレージアセットページにカスタムウィジェットを追加すると、そのウィジェットがすべてのストレージアセットのアセットページに表示されます。
