---
sidebar: sidebar 
permalink: concept-write-speed.html 
keywords: write speed, high write speed, normal write speed, nvfail, writing speed, ldm, low durability mode 
summary: BlueXPを使用すると、Cloud Volumes ONTAP で通常または高速の書き込み速度を選択できます。書き込み速度を選択する前に、高速書き込みを使用する場合の標準設定と高設定の違い、およびリスクと推奨事項を理解しておく必要があります。 
---
= 書き込み速度
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXPを使用すると'ほとんどのCloud Volumes ONTAP 構成で通常の書き込み速度または高速の書き込み速度を選択できます書き込み速度を選択する前に、高速書き込みを使用する場合の標準設定と高設定の違い、およびリスクと推奨事項を理解しておく必要があります。



== 通常の書き込み速度

通常の書き込み速度を選択した場合、データはディスクに直接書き込まれます。データをディスクに直接書き込んだ場合、計画外のシステム停止が発生した場合や、計画外のシステム停止が発生した場合のデータ損失の可能性を低減します（ HA ペアのみ）。

デフォルトでは、通常の書き込み速度が使用されます。



== 高速の書き込み速度

高速書き込みを選択すると、データはディスクに書き込まれる前にメモリにバッファされるため、書き込みパフォーマンスが向上します。このキャッシュにより、計画外のシステム停止が発生した場合にデータが失われる可能性があります。

計画外のシステム停止が発生した場合に失われる可能性があるデータの量は、最後の 2 つの整合ポイントの範囲です。整合ポイントとは、バッファされたデータをディスクに書き込むことです。整合ポイントは、書き込みログがいっぱいになったとき、または 10 秒後（どちらか早い方）に発生します。ただし、クラウドプロバイダが提供するストレージのパフォーマンスが整合ポイントの処理時間に影響する可能性があります。



=== 高速書き込みを使用する場合

高速の書き込みパフォーマンスが求められるワークロードで、計画外のシステム停止が発生した場合や、計画外のシステム停止（ HA ペアのみ）が伴うカスケード障害が発生した場合のデータ損失リスクに対処できる場合は、高速の書き込み速度を使用することを推奨します。



=== 高速書き込みを使用する場合の推奨事項

高速の書き込み速度を有効にする場合は、アプリケーションレイヤでの書き込み保護を確保するか、またはデータ損失が発生した場合にアプリケーションで許容されるようにする必要があります。

ifdef::aws[]



=== AWS で HA ペアを使用した場合の高速の書き込み速度

AWS の HA ペアで高速の書き込み速度を有効にする場合は、複数の Availability Zone （ AZ ；アベイラビリティゾーン）環境と単一の AZ 環境の保護レベルの違いを理解しておく必要があります。複数の AZ に HA ペアを導入すると、耐障害性が向上し、データ損失の可能性を軽減できます。

link:concept-ha.html["AWS の HA ペアについて詳しくは、こちらをご覧ください"]。

endif::aws[]



=== 高速の書き込み速度をサポートする構成

すべての Cloud Volumes ONTAP 構成で高速書き込みがサポートされるわけではありません。デフォルトでは、これらの構成では通常の書き込み速度が使用されます。

ifdef::aws[]



==== AWS

シングルノードシステムを使用する場合、 Cloud Volumes ONTAP では、すべてのインスタンスタイプで高速な書き込み速度がサポートされます。

9.8 リリース以降では、 Cloud Volumes ONTAP でサポートされているほぼすべての EC2 インスタンスタイプを使用する場合、 HA ペアでの高速書き込みがサポートされます。ただし、 m5.xlarge と r5.xlarge は除きます。

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-aws.html["Cloud Volume が提供する Amazon EC2 インスタンスの詳細については、こちらをご覧ください ONTAP はをサポートします"^]。

endif::aws[]

ifdef::azure[]



==== Azure

シングルノードシステムを使用する場合、 Cloud Volumes ONTAP では、すべての種類の VM で高速な書き込み速度がサポートされます。

HA ペアを使用する場合、 Cloud Volumes ONTAP では 9.8 リリース以降、複数の種類の VM で高速の書き込み速度がサポートされます。にアクセスします https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html["Cloud Volumes ONTAP リリースノート"^] をクリックして、高速の書き込み速度をサポートする VM タイプを確認します。

endif::azure[]

ifdef::gcp[]



==== Google Cloud

シングルノードシステムを使用する場合、 Cloud Volumes ONTAP では、すべての種類のマシンで高速な書き込み速度がサポートされます。

HAペアを使用する場合、Cloud Volumes ONTAP 9.13.0リリース以降では、いくつかのタイプのVMで高速の書き込み速度がサポートされます。にアクセスします https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html#supported-configurations-by-license["Cloud Volumes ONTAP リリースノート"^] をクリックして、高速の書き込み速度をサポートする VM タイプを確認します。

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["Cloud の Google Cloud マシンタイプの詳細をご覧ください Volume ONTAP はをサポートします"^]。

endif::gcp[]



== 書き込み速度を選択する方法

を作成するときに、書き込み速度を選択できます 新しい作業環境を構築できます link:task-modify-write-speed.html["既存のシステムの書き込み速度を変更する"]。



== データ損失が発生した場合の予測

高速の書き込み速度が原因でデータ損失が発生した場合、Event Management System（EMS；イベント管理システム）で次の2つのイベントが報告されます。

* Cloud Volumes ONTAP 9.12.1以降
+
 NOTICE nv.data.loss.possible: An unexpected shutdown occurred while in high write speed mode, which possibly caused a loss of data.
* Cloud Volumes ONTAP 9.11.0～9.11.1
+
 DEBUG nv.check.failed: NVRAM check failed with error "NVRAM disabled due to dirty shutdown with High Write Speed mode"
+
 ERROR wafl.root.content.changed: Contents of the root volume '' might have changed. Verify that all recent configuration changes are still in effect..
* Cloud Volumes ONTAP 9.8～9.10.1
+
 DEBUG nv.check.failed: NVRAM check failed with error "NVRAM disabled due to dirty shutdown"
+
 ERROR wafl.root.content.changed: Contents of the root volume '' might have changed. Verify that all recent configuration changes are still in effect.


この場合、Cloud Volumes ONTAP をブートして、ユーザの手を煩わせることなくデータを提供できるようにする必要があります。



== データ損失が発生した場合のデータアクセスの停止方法

データ損失について懸念がある場合、データ損失時にアプリケーションの実行を停止し、データ損失の問題に適切に対処したあとでデータアクセスを再開するには、 CLI から NVFAIL オプションを使用してこの目標を達成します。

をクリックして NVFAIL オプションを有効にします:: `vol modify -volume <vol-name> -nvfail on`
をクリックして NVFAIL 設定を確認します:: `vol show -volume <vol-name> -fields nvfail`
NVFAIL オプションを無効にする場合:: `vol modify -volume <vol-name> -nvfail off`


データ損失が発生した場合、 NVFAIL が有効になっている NFS または iSCSI ボリュームは、データ処理を停止する必要があります（ステートレスプロトコルである CIFS への影響はありません）。詳細については、を参照してください https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-mgmt-dr/GUID-40D04B8A-01F7-4E87-8161-E30BD80F5B7F.html["NFS ボリュームまたは LUN へのアクセスに対する NVFAIL の影響"^]。

をクリックして NVFAIL 状態を確認します:: `vol show -fields in-nvfailed-state`


データ損失の問題に適切に対処したら、 NVFAIL 状態を解消でき、ボリュームへのデータアクセスが可能になります。

をクリックして NVFAIL 状態を解消します:: `vol modify -volume <vol-name> -in-nvfailed-state false`

