---
sidebar: sidebar 
permalink: faq-config-support.html 
keywords: FAQ, Frequently asked questions, questions, configuration, 
summary:  
---
= 構成とサポートされるデバイス
:allow-uri-read: 


[role="lead"]
この FAQ では、 Cloud Insights 構成とサポートされているデバイスに関する一般的な質問に回答しています



== Cloud Insights で環境が変更されていませんか？

いいえCloud Insights は、環境に関する情報を収集する読み取り専用ツールです。Cloud Insights では、アセットや構成を一切変更することはありません。



== Cloud Insights でデバイスに必要な権限レベルのアクセス権は何ですか。

デバイスがサポートしている場合、ほとんどの場合、読み取り専用アクセスが必要です。読み取り専用アクセスを許可しないソリューションもあるため、適切な昇格されたアクセス許可が必要になります。



== Cloud Insights はどれくらいの頻度で情報を収集しますか。

Cloud Insights は通常、パフォーマンスデータを 5 分ごとに収集し、論理構成と物理構成を 30 分ごとに検出しますCloud Insights では、推奨されるベストプラクティスや拡張性に基づいてデフォルトのポーリング間隔が設定されますが、それらの間隔についてはユーザが完全に制御することができます。



== Cloud Insights が環境に与える影響

Cloud Insights のエージェントレス、アウトオブバンド、パッシブ IP 通信により、セットアップ、メンテナンス、データセンターエコシステムへの影響を最小限に抑えることができます。Cloud Insights のパフォーマンス開発チームは、データセンターのパフォーマンスへの影響を最小限に抑えるために、パフォーマンスの監視というアクティビティで大きな効果を発揮します。通常の運用環境では影響はごくわずかで、利用率の高いテクノロジプラットフォームやパフォーマンスの低いテクノロジプラットフォームで、リラックスした状態や強化が可能です。詳細については、『 Cloud Insights インストールガイド』を参照してください。



== Cloud Insights ですべてのホスト / VM を一覧表示するにはどうすればよいですか。

Cloud Insights は、ウィジェットとクエリリスト機能を補完するもので、データセンター資産のインベントリスタイルリストを提供します。スピンドルとその間に配置されたさまざまな構成要素を仮想マシンで一覧表示することができ、クエリ、ウィジェット、ダッシュボード、データウェアハウスレポートにアクセスできます。 RESTful API からアクセスできます。



== Cloud Insights は、関連する非ハイパーバイザーホスト（物理サーバ）に対して同じタイプのサポートを提供しますか。

VMware などのハイパーバイザーは、 ESXi ホストとその仮想マシン（ VM ）に関する詳細情報を提供します。物理サーバの場合、 Cloud Insights はホスト HBA までの指標を収集します。Cloud Insights は、特許出願中のテクノロジを使用して物理サーバを検出する独自の方法を採用しています。ストレージやスイッチが検出されると、物理サーバのホスト名がファブリックエイリアス情報に含まれます。Cloud Insights は、これらのホスト名を選択し、 DNS に一致させて、ホストを自動的に Cloud Insights に割り当てます。この方法により、手動での入力更新やツールインベントリのメンテナンスが必要なくなります。



== Cloud Insights では、異機種混在環境全体で同じデバイスのメトリック深度（パリティ）が提供されますか。

サードパーティのプラットフォームとベンダーのテクノロジ全体で、標準化、共通性、および命名方法にはさまざまなレベルがあります。Cloud Insights は、容量とパフォーマンスの情報を一貫したフレームワークに正規化しようとします。容量やパフォーマンスの一部の指標は、 IOPS 、レイテンシ、物理容量など、デバイスのカウンタからネイティブに提供されます。カウンタを指定しない場合、 Cloud Insights は値を集計できます（たとえば、基盤となるボリュームの IOPS または容量を合計するなど）。どちらも使用できない場合は、 Cloud Insights はさまざまな計算アルゴリズムを通じて指標値の算出を試みます。Cloud Insights には、 Cloud Insights が現在収集していない指標を追加で組み込むための、汎用的な SNMP 統合機能があります。



== Cloud Insights はファイバチャネルスイッチをサポートしていますか。

はい。お客様のストレージ資産からデータを収集するだけでなく、 Cloud Insights はお客様の環境内の Cisco 、 Brocade 、 QLogic スイッチからインベントリデータとパフォーマンスデータも取得します。

== インフラストラクチャ全体のトポロジビューは使用できますか ? Cloud Insights には「エンドツーエンドの可視性」が表示されますか。

はい。 Cloud Insights は、論理構成要素と物理構成要素を動的に検出してマッピングし、コンピューティング、ファブリック、仮想化、バックエンドストレージに関するエンドツーエンドのトポロジビューを対話型で提供します。トポロジアイコンを使用すると、影響を受けるリソースへのクイック起動ナビゲーションが可能になり、共有ストレージ環境でのワークロードや違反の特定に役立ちます。
