---
sidebar: sidebar 
permalink: io_density_nonroot.html 
keywords: notifications, annotations, queries, applications, 
summary: IO 密度 
---
= I/O 密度のデータに内部データボリュームのみが含まれていることを確認する


[role="lead"]
ネットアップストレージシステムでは、ルートアグリゲートに、ストレージシステムの管理と制御に使用する特別なディレクトリと構成ファイルが含まれています。これらの処理を実行すると、ルートアグリゲートで大量のアクティビティが発生する可能性があります。I/O 密度が高い上位 10 個の内部ボリュームを Cloud Insights で照会すると、その結果の中にルートアグリゲートも含まれることがあります。

環境を監視する際には、どの内部データボリュームが高い I/O 密度を生成しているかを特定することが重要です。データボリュームだけを正確に特定するには、ネットアップの内部ボリュームを、 I/O 密度の監視に使用するクエリから分離する必要があります。

このガイドでは、ネットアップのルートアグリゲートを簡単に特定し、それらを内部ボリュームのクエリの結果から分離する方法と、システムにネットアップの新しいルートアグリゲートが追加されるたびにそれらを除外するルールを作成する方法について説明します。I/O 密度レポートに内部データボリュームだけの情報を出力するには、 Cloud Insights の次の機能を使用します。

* Cloud Insights で監視しているネットアップのルートアグリゲートを特定するクエリを作成する。
* ネットアップのルートアグリゲートのそれぞれにアノテーションを割り当てる。
* ネットアップのルートアグリゲートを除外するためのアノテーションルールが作成されます。




== 環境内でネットアップのルートアグリゲートを特定するクエリの作成

クエリは、ユーザが選択した条件に基づいて、細かいレベルまで検索する機能です。クエリを使用すると、ネットアップのルートアグリゲートが含まれている環境内の内部ボリュームを検索できます。

.手順
. Cloud Insights で、環境内のネットアップのルートアグリゲートを特定するクエリを作成します。 * Queries > + New Query > Storage Pool *
. ルートアグリゲートの名前を入力します
+
この例では、名前に「 aggr0 」を使用します。アグリゲートの作成時には、次の要件に従って名前を指定する必要があります。

+
** 先頭の文字にはアルファベットまたはアンダースコア（ _ ）を使用する必要があります。
** アルファベット、数字、アンダースコアのみを使用できます。
** 250 文字以内で指定します。




アグリゲートの名前は通常、 aggr0 、 aggr_0 などの形式にします。環境内のネットアップのルートアグリゲートをすべて特定するには、反復的なプロセスが必要となる場合があります。

. [ 保存（ Save ） ] をクリックし、新しい照会の名前を入力する。
+
前述のとおり、この作業は反復的なプロセスになる場合があり、ネットアップのすべてのルートアグリゲートを特定するために複数のクエリが必要になることがあります。





== クエリで返されるルートボリューム用のアノテーションを作成します

アノテーションはアセットに割り当てる特殊なメモで、アノテーションによってアセットをフィルタすることができます。作成したアノテーションは、環境内のネットアップのルートアグリゲートを特定し、 IO 密度が高い内部ボリュームのリストに含まれないようにするために使用します。

「 High I/O Density 」レポートから除外するルートアグリゲートをすべて特定しておく必要があります。

.手順
. 特定したすべてのネットアップルートアグリゲートをクエリに関連付けるためのアノテーションを作成します。 * Manage > Annotations *
+
.. アノテーションの名前として「 * RootAggr 」と入力します
.. アノテーションの概要を入力します。 * 「 High I/O Density 」リストからルートアグリゲートを削除します。 *
.. アノテーションのタイプとして「 * Boolean * 」と入力します


. [ 保存（ Save ） ] をクリックします。




== I/O 密度に関するレポートから特定のアグリゲートを自動的に除外するためのアノテーションルールの作成

アノテーションを個々のアセットに手動で適用する代わりに、アノテーションルールを使用して複数のアセットに自動的にアノテーションを適用することができます。アノテーションルールは、ユーザが作成するクエリに基づいてシステム上で実行されるもので、新しいアセットを既存のアセットセットに追加します。これらのアセットセットを包含から除外すると、新しいアセットも自動的に除外されます。

環境内で特定したネットアップのルートアグリゲートを識別するクエリを作成し、保存しておく必要があります。

.手順
. Cloud Insights メニューで、 * Manage > Annotations * をクリックします
. [ 追加（ Add ） ] をクリックします。
. 次の手順を実行します。
+
.. [ 名前 ] ボックスに、ルール * RootAggrExclude* を記述する一意の名前を入力します
.. Query をクリックし、アノテーションルールを * Aggregate0 * に適用するために Cloud Insights が使用する Query を選択します
.. Annotation をクリックして ':* ルートアグリゲート除外 * を選択します
.. 「 * Value * 」をクリックし、「 * True * 」と入力します



