---
sidebar: sidebar 
permalink: reporting_creating_custom_reports.html 
summary: レポートオーサリングツールを使用してカスタム（「アドホック」）レポートを作成する 
keywords: reporting, cognos, data warehouse, dwh, ad-hoc, custom 
---
= カスタムレポートの作成
:allow-uri-read: 


[role="lead"]
レポートオーサリングツールを使用してカスタムレポートを作成できます。作成したレポートは、保存して定期的に実行できます。レポートの結果は、自分や他のユーザに E メールで自動送信できます。


NOTE: レポート機能は Cloud Insights で使用できます link:concept_subscribing_to_cloud_insights.html["Premium Edition の場合"]。

このセクションの例では、次のプロセスについて説明します。このプロセスは、 Cloud Insights レポート作成のすべてのデータモデルに使用できます。

* レポートで回答する質問を特定しています
* 結果をサポートするために必要なデータを決定する
* レポートのデータ要素を選択しています


カスタムレポートを設計する前に、いくつかの前提条件となるタスクを完了しておく必要があります。これらの作業を完了しないと、不正確または不完全なレポートが生成される可能性があります。

たとえば、デバイスの識別プロセスを完了していないと、正確な容量レポートが生成されません。また、アノテーション（階層、ビジネスユニット、データセンターなど）の設定が完了していないと、ドメイン全体でデータが正確にレポートされなかったり、一部のデータに「 N/A 」と表示されたりする可能性があります。

レポートを設計する前に、次の作業を完了してください。

* すべてを設定します link:task_configure_data_collectors.html["データコレクタ"] 適切です。
* 環境内のデバイスとリソースにアノテーション（階層、データセンター、ビジネスユニットなど）を入力します。Cloud Insights レポートでは履歴情報が収集されるため、レポートの生成前にアノテーションを確定しておくことを推奨します。




=== レポート作成プロセス

カスタム（「アドホック」とも呼ばれる）レポートを作成するプロセスには、いくつかのタスクが含まれます。

* レポートの結果を計画します。
* 結果をサポートするデータを特定します。
* データが格納されているデータモデル（ Chargeback データモデル、 Inventory データモデルなど）を選択します。
* レポートのデータ要素を選択します。
* 必要に応じて、レポート結果の書式設定、並べ替え、フィルタリングを行います。




==== カスタムレポートの結果を計画する

レポートオーサリングツールを開く前に、必要な結果についてレポートで計画することができます。レポートオーサリングツールでは、レポートを簡単に作成でき、詳細な計画は必要ないかもしれませんが、レポートを必用としている担当者にレポートの要件について確認しておくことを推奨します。

* 回答の正確な質問を特定します。例：
+
** 残りの容量
** ビジネスユニットあたりのチャージバックコスト
** 階層別の容量 - 各ビジネスユニットが適切なストレージ階層に配置されているか
** 必要な電力と冷却コストを予測するにはどうすればよいですか。（リソースにアノテーションを追加することで、カスタマイズしたメタデータを追加）


* 回答をサポートするために必要なデータ要素を特定します。
* 回答に表示するデータ間の関係を特定します。「容量に関連するポートを表示したい」など、問題に論理的でない関係を含めないでください。
* データに必要な計算があれば特定します。
* 結果を制限するために必要なフィルタリングのタイプを決定します。
* 現在のデータまたは履歴データのどちらを使用する必要があるかを判断します。
* レポートにアクセス権を設定してデータの閲覧を特定のユーザに制限する必要があるかどうかを判断します。
* レポートの配布方法を特定します。たとえば、設定されたスケジュールで電子メールで送信するか、チームコンテンツフォルダ領域に含める必要がありますか？
* レポートの管理者を決定します。これは、設計の複雑さに影響する可能性があります。
* レポートのモックアップを作成します。




==== レポートの設計に関するヒント

レポートを設計するときは、いくつかのヒントが役立つことがあります。

* 現在のデータと履歴データのどちらを使用する必要があるかを判断します。
+
ほとんどのレポートでは、 Cloud Insights で使用可能な最新のデータについてのみレポートする必要があります。

* Cloud Insights レポートには、容量とパフォーマンスに関する履歴情報は表示されますが、インベントリに関する履歴情報は表示されません。
* すべてのユーザにすべてのデータが表示されますが、データを特定のユーザに制限しなければならない場合もあります。
+
ユーザごとに情報を分割するには、レポートを作成し、レポートにアクセス権限を設定します。





== レポートデータモデル

Cloud Insights には複数のデータモデルが含まれており、事前定義済みのレポートを選択するか、または独自のカスタムレポートを作成することができます。

各データモデルにはシンプルなデータマートと高度なデータマートが含まれています。

* シンプルなデータマートを使用すると、最もよく使用されるデータ要素に簡単にアクセスできます。このデータマートには、 Data Warehouse データの最新の Snapshot だけが含まれており、履歴データは含まれていません。
* 高度なデータマートは、シンプルなデータマートに含まれるすべての値と詳細を提供し、履歴データ値へのアクセスを含みます。




=== Capacity データモデル

ストレージ容量、ファイルシステム利用率、内部ボリュームの容量、ポート容量、 qtree 容量に関する回答の情報を表示します。 仮想マシン（ VM ）の容量が必要です。Capacity データモデルは、複数の容量データモデルをまとめたコンテナです。このデータモデルを使用して、さまざまなタイプの情報を収集したレポートを作成できます。



=== Storage and Storage Pool Capacity データモデル

ストレージとストレージプール、および物理ストレージプールと仮想ストレージプールの両方のデータについて、ストレージ容量のリソース計画に関する回答の情報を確認できます。このシンプルなデータモデルを使用すると、フロアの容量に関連する回答の質問や、一定期間にわたる階層別およびデータセンター別のストレージプールの使用容量に関する情報を確認できます。容量に関するレポートを初めて作成する場合は、シンプルでターゲットが限定されたこのデータモデルを使用してください。このデータモデルを使用すると、次のような回答の情報を確認できます。

* 物理ストレージの容量しきい値の 80% に達するまでの予測日
* 特定の階層のアレイ上の物理ストレージ容量
* メーカー、ファミリー、およびデータセンター別のストレージ容量
* すべての階層のアレイにおけるストレージ利用率のトレンド
* 利用率が最も高い上位 10 個のストレージシステム
* ストレージプールのストレージ利用率のトレンド
* 割り当て済みの容量
* 割り当て可能な容量




=== File System Utilization データモデル

このデータモデルを使用すると、ファイルシステムレベルでホスト別の容量利用率を確認できます。管理者は、ファイルシステムごとの割り当て済み容量と使用済み容量、およびファイルシステムタイプを確認したり、ファイルシステムタイプ別のトレンドを特定したりできます。このデータモデルを使用すると、次の情報を回答で確認できます。

* ファイルシステムのサイズ
* データはどこに保管され、どのようにアクセスされるか（ローカル、 SAN など）。
* ファイルシステム容量の過去の傾向は何ですか。そして、これに基づいて、将来のニーズにどのような対応を期待できますか？




=== Internal Volume Capacity データモデル

一定期間にわたる内部ボリュームの使用済み容量、割り当て済みの容量、および使用容量に関する回答の情報を確認できます。

* 利用率が事前に定義されたしきい値を上回っている内部ボリューム
* トレンドに基づいて容量が不足する危険がある内部ボリュームはどれですか？8 内部ボリュームの使用済み容量と割り当て済み容量の比較




=== Port Capacity データモデル

一定期間にわたるスイッチポートの接続、ポートのステータス、およびポートの速度に関する回答の情報を確認できます。次のような回答に関する質問を参考に、新しいスイッチの購入を計画してください。 How can I create a port consumption that Predicts resource （ port ） availability （データセンター、スイッチベンダー、ポート速度に応じた）？

* 容量不足になり、データ速度、データセンター、ベンダー、ホストポートとストレージポートの数が提供される可能性があるポートはどれですか？
* 一定期間にわたるスイッチポートの容量のトレンド
* ポートの速度
* 必要なポート容量のタイプ、および特定のポートタイプまたはベンダーで容量が不足しそうな組織
* いつまでに容量を購入して利用可能にするべきか




=== Qtree Capacity データモデル

一定期間にわたる qtree 利用率のトレンドを（使用済み容量と割り当て済み容量の比較などのデータを使用して）確認できます。ビジネスエンティティ、アプリケーション、階層、サービスレベルなど、さまざまなディメンション別に情報を表示できます。このデータモデルを使用すると、次の情報を回答で確認できます。

* アプリケーションまたはビジネスエンティティごとに設定されている制限値に対する qtree の使用済み容量
* キャパシティプランニングを実施するための使用済み容量と空き容量のトレンド
* 使用容量が最も多いビジネスエンティティ
* 使用容量が最も多いアプリケーション




=== VM Capacity データモデル

仮想環境とその使用容量を報告できます。このデータモデルを使用すると、 VM とデータストアの一定期間にわたる使用容量の変化を報告できます。このデータモデルは、シンプロビジョニングと仮想マシンのチャージバックデータも提供します。

* VM とデータストアにプロビジョニングされた容量に基づいて容量のチャージバックを決定する方法
* VM で使用されていない容量、およびそのうちの空き容量、孤立している容量、その他の状態の容量
* 消費傾向に基づいて何を購入する必要がありますか？
* ストレージのシンプロビジョニングと重複排除のテクノロジを使用することで達成される Storage Efficiency による削減効果


VM Capacity データモデルの容量は、仮想ディスク（ VMDK ）から取得されます。つまり、 VM Capacity データモデルを使用した場合の VM のプロビジョニング済みサイズは、その VM の仮想ディスクのサイズです。これは、 Cloud Insights の仮想マシンビューでプロビジョニングされている容量とは異なります。プロビジョニングされている容量には、 VM 自体のプロビジョニングサイズが表示されます。



=== Volume Capacity データモデル

環境内のボリュームのすべての要素を分析し、ベンダー、モデル、階層、サービスレベル、およびデータセンター別にデータを整理できます。

孤立ボリューム、未使用ボリューム、および保護ボリューム（レプリケーションに使用）に関連する容量を表示できます。また、さまざまなボリュームテクノロジ（ iSCSI または FC ）を表示したり、アレイの仮想化の問題について仮想ボリュームと非仮想ボリュームを比較したりすることもできます。

このデータモデルを使用すると、次のような回答の情報を確認できます。

* 利用率が事前に定義されたしきい値を上回っているボリューム
* 孤立ボリューム容量のデータセンターにおけるトレンド
* 仮想化またはシンプロビジョニングされているデータセンター容量
* レプリケーション用に予約する必要があるデータセンター容量




=== Chargeback データモデル

ストレージリソース（ボリューム、内部ボリューム、 qtree ）の使用済み容量と割り当て済み容量に関する回答の情報を確認できます。このデータモデルは、ストレージ容量のチャージバックとアカウンタビリティの情報をホスト、アプリケーション、およびビジネスエンティティ別に提供します。現在のデータと履歴データの両方が含まれます。レポートデータは、サービスレベルとストレージ階層で分類できます。

このデータモデルを使用すると、ビジネスエンティティで使用されている容量を検出することでチャージバックレポートを生成できます。このデータモデルでは、複数のプロトコル（ NAS 、 SAN 、 FC 、 iSCSI など）についてのレポートをまとめて作成できます。

* 内部ボリュームがないストレージの場合、チャージバックレポートにはボリューム別のチャージバックが表示されます。
* 内部ボリュームがあるストレージの場合：
+
** ビジネスエンティティがボリュームに割り当てられている場合、チャージバックレポートにはボリューム別のチャージバックが表示されます。
** ビジネスエンティティがボリュームではなく qtree に割り当てられている場合、チャージバックレポートには qtree 別のチャージバックが表示されます。
** ビジネスエンティティがボリュームにも qtree にも割り当てられていない場合、チャージバックレポートには内部ボリュームが表示されます。
** ボリューム別、 qtree 別、または内部ボリューム別のチャージバックを表示するかどうかは内部ボリュームごとに決定されるため、同じストレージプール内の別々の内部ボリュームで異なるレベルのチャージバックが表示される可能性があります。




容量ファクトはデフォルトの期間後にパージされます。詳細については、 Data Warehouse のプロセスを参照してください。

Chargeback データモデルを使用するレポートには、 Storage Capacity データモデルを使用するレポートとは異なる値が表示される場合があります。

* ネットアップストレージシステムでないストレージアレイの場合、両方のデータモデルのデータは同じです。
* NetApp および Celerra のストレージシステムの場合、 Chargeback データモデルは（ボリューム、内部ボリューム、または qtree の） 1 つのレイヤを使用して料金を請求し、 Storage Capacity データモデルは（ボリュームと内部ボリュームの）複数のレイヤを使用して料金を加算します。




=== Inventory データモデル

ホスト、ストレージシステム、スイッチ、ディスク、テープなどのインベントリリソースに関する回答の質問にお答えします。 qtree 、クォータ、仮想マシンとサーバ、および汎用デバイスです。Inventory データモデルには、レプリケーション、 FC パス、 iSCSI パス、 NFS パス、および違反に関する情報を表示するサブマートが複数含まれています。Inventory データモデルには履歴データは含まれません。このデータを使用して回答で確認できる情報

* 所有しているアセットとその場所
* アセットの使用者
* 所有しているデバイスの種類と、デバイスのコンポーネントを教えてください。
* OS あたりのホスト数とホスト上のポート数
* 各データセンターには、ベンダーごとにどのようなストレージアレイがありますか。
* 各データセンターには、ベンダーあたりいくつのスイッチがありますか。
* ライセンスが設定されていないポートの数
* 使用しているベンダーのテープ、および各テープのポート数。レポートの作成を開始する前に、特定されたすべての汎用デバイスを再確認します。
* ホストとストレージボリュームまたはテープ間のパス
* 汎用デバイスとストレージボリュームまたはテープ間のパス
* データセンターごとの各タイプの違反数
* レプリケートされた各ボリュームの、ソースボリュームとターゲットボリューム
* Fibre Channel ホストの HBA とスイッチとの間にファームウェアの互換性の問題またはポート速度の不一致があるか




=== Performance データモデル

ボリューム、アプリケーションボリューム、内部ボリューム、スイッチ、アプリケーションのパフォーマンスに関する回答の質問に回答できます。 VM 、 VMDK 、 ESX と VM 、ホスト、およびアプリケーションノードです。このデータモデルを使用すると、回答に複数のタイプのパフォーマンス管理に関する情報を記載したレポートを作成できます。

* 特定の期間に使用またはアクセスされていないボリュームまたは内部ボリューム
* アプリケーション用のストレージ（未使用）に関する潜在的な構成ミスを特定できるか？
* アプリケーションの全体的なアクセス動作パターン
* 特定のアプリケーションに階層型ボリュームが適切に割り当てられているか
* アプリケーションのパフォーマンスに影響を与えずに、実行中のアプリケーションに安価なストレージを使用できますか？
* 現在設定されているストレージへのアクセスが多いアプリケーション


スイッチパフォーマンスのテーブルを使用すると、次の情報を取得できます。

* 接続されたポート経由でホストトラフィックが分散されているか。
* 多数のエラーが発生しているスイッチまたはポート
* ポートパフォーマンスに基づいて最も使用されているスイッチはどれですか？
* 使用率の低いスイッチのうち、ポートのパフォーマンスに基づくものは何ですか。
* ポートのパフォーマンスに基づくホストのトレンド分析スループット
* 特定の 1 つのホスト、ストレージシステム、テープ、またはスイッチの過去 X 日間のパフォーマンス利用率
* 特定のスイッチでトラフィックを生成しているデバイス（たとえば、利用率の高いスイッチを使用しているデバイス）
* 環境内の特定のビジネスユニットのスループット


ディスクパフォーマンスのテーブルを使用すると、次の情報を取得できます。

* ディスクのパフォーマンスデータに基づく、指定されたストレージプールのスループット
* 最も使用されているストレージプール
* 特定のストレージのディスク利用率の平均
* ディスクパフォーマンスデータに基づくストレージシステムまたはストレージプールの使用状況のトレンド
* 特定のストレージプールのディスク使用率のトレンド


VM と VMDK のパフォーマンスのテーブルを使用すると、次の情報を取得できます。

* 仮想環境のパフォーマンスが最適化されているか
* 最も高いワークロードを報告している VMDK
* 異なるデータストアにマッピングされた VM から報告されたパフォーマンスを使用して、階層化の再決定を行うにはどうすればよいですか。


パフォーマンスデータモデルには、階層の妥当性、アプリケーション用のストレージの構成ミス、およびボリュームと内部ボリュームの最終アクセス時刻を特定するための情報が含まれています。このデータモデルは、応答時間、 IOPS 、スループット、保留中の書き込み数、アクセスステータスなどのデータを提供します。



=== Storage Efficiency データモデル

一定期間にわたるストレージの削減率と可能性を追跡できます。このデータモデルには、プロビジョニング済み容量のデータだけでなく、使用済みまたは消費済みの容量（物理的な測定値）も格納されます。たとえば、シンプロビジョニングが有効になっている場合、 Cloud Insights はデバイスから取得された容量を示します。また、このモデルを使用して、重複排除が有効な場合の効率を判断することもできます。Storage Efficiency データマートを使用すると、回答に関するさまざまな情報を確認できます。

* シンプロビジョニングと重複排除を実装した場合の Storage Efficiency による削減効果
* データセンター全体でのストレージ削減量
* 過去の容量のトレンドに基づいて、ストレージを追加購入する必要があるのはいつですか？
* シンプロビジョニングや重複排除などのテクノロジを有効にした場合の容量の増加
* ストレージ容量にリスクがありますか？




=== データモデルのファクトテーブルとディメンションテーブル

各データモデルには、ファクトテーブルとディメンションテーブルの両方が含まれています。

* ファクトテーブル：量、物理容量、使用可能な容量など、測定されたデータが含まれます。ディメンションテーブルへの外部キーが含まれます。
* ディメンションテーブル：データセンターやビジネスユニットなど、ファクトに関する説明が含まれます。ディメンションはデータを分類する構造であり、多くの場合、複数の階層で構成されます。ディメンション属性は、ディメンション値の説明に役立ちます。


（レポート内の列に表示される）複数のディメンション属性を使用して、データモデルに含まれる各ディメンションのデータをアクセスするレポートを作成します。



=== データモデル要素で使用される色

データモデル要素の色には意味があります。

* 黄色のアセット：測定値を表します。
* 黄色以外のアセット：属性を表します。これらの値は集計されません。




=== 1 つのレポートで複数のデータモデルを使用する

通常は、レポートごとに 1 つのデータモデルを使用します。ただし、複数のデータモデルのデータを結合したレポートを作成することができます。

複数のデータモデルのデータを結合したレポートを作成するには、ベースとして使用するデータモデルを 1 つ選択し、追加のデータマートからデータを収集する SQL クエリを作成します。SQL の Join 機能を使用して、複数のクエリのデータを 1 つのクエリに結合し、レポートの作成に使用できます。

たとえば、各ストレージアレイの現在の容量を確認し、アレイのカスタムアノテーションを取得するとします。このレポートは、 Storage Capacity データモデルを使用して作成できます。Current Capacity テーブルとディメンションテーブルの要素を使用し、別途 SQL クエリを追加して Inventory データモデルのアノテーション情報にアクセスします。最後に、ストレージ名と結合条件を使用して Inventory のストレージデータを Storage Dimension テーブルにリンクして、データを結合します。
