---
sidebar: sidebar 
permalink: reporting_overview.html 
summary: Cloud Insights を使用して、データの事前定義およびカスタムレポートを作成できます。 
keywords: reporting, cognos, data warehouse, dwh 
---
= Cloud Insights レポート概要
:allow-uri-read: 


[role="lead"]
Cloud Insights Reporting は、事前定義済みのレポートを表示したりカスタムレポートを作成したりできる、ビジネスインテリジェンスツールです。


NOTE: レポート機能は Cloud Insights で使用できます link:concept_subscribing_to_cloud_insights.html["Premium Edition の場合"]。

Cloud Insights レポートを使用すると、次のタスクを実行できます。

* 事前定義済みのレポートを実行します
* カスタムレポートを作成する
* レポートの形式と配信方法をカスタマイズする
* レポートが自動的に実行されるようにスケジュールを設定する
* レポートを E メールで送信
* データのしきい値を色で表します


Cloud Insights レポートでは、チャージバック、消費分析、予測などの領域用のカスタムレポートを生成できます。また、回答に関する次のような質問にも対応できます。

* 所有しているインベントリ
* インベントリの場所
* アセットの使用者
* ビジネスユニットに割り当てられているストレージのチャージバック
* ストレージ容量の追加購入が必要になるまでの期間
* ビジネスユニットが適切なストレージ階層に配置されているか。
* 1 カ月、 1 四半期、 1 年のストレージ割り当ての変化




== Cloud Insights レポートにアクセスしています

メニューの [*Reports] リンクをクリックすると、 Cloud Insights レポートにアクセスできます。

Reporting インターフェイスに移動します。Cloud Insights では、レポート作成エンジンに IBM Cognos Analytics を使用しています。Reporting クレデンシャルを使用してログインします。



== ETL とは

Reporting では、「 Data Warehouse 」と「 ETL 」という用語が使用されます。ETL は、「抽出、変換、読み込み」の略です。ETL プロセスでは、 Cloud Insights で収集されたデータが取得されて、レポート用の形式に変換されます。「 Data Warehouse 」は、レポートに使用できる収集データを表します。

ETL プロセスは、次の個別プロセスで構成されます。

* * 抽出 *: Cloud Insights からデータを取得します。
* * Transform * ： Cloud Insights から抽出されたデータにビジネスロジックのルールまたは関数を適用します。
* * ロード *: 変換されたデータをデータウェアハウスに保存して、レポート作成に使用します。

