---
sidebar: sidebar 
permalink: reporting_user_roles.html 
summary: Cloud Insights レポートで実行できる操作は、ユーザロールによって異なります。 
keywords: reporting, cognos, data warehouse, dwh, users, roles, user roles 
---
= Cloud Insights レポートユーザーの役割


[role="lead"]
Cloud Insights Premium Edition と Reporting を使用している場合は、環境内のすべての Cloud Insights ユーザに、 Reporting アプリケーションへのシングルサインオン（ SSO ）ログイン（など）が付与されます Cognos ）を参照してくださいメニューの * Reports * リンクをクリックすると、自動的に Reporting にログインします。

Cloud Insights でのユーザロールによって、 Reporting ユーザのロールが決まります。

|===


| Cloud Insights ロール | Reporting ロール | レポート権限 


| ゲスト | 消費者 | レポートの表示、スケジュール設定、実行、および言語やタイムゾーンなどの個人設定を行うことができます。消費者は、レポートの作成や管理タスクの実行はできません。 


| ユーザ | 作成者 | すべてのコンシューマ機能を実行できるだけでなく、レポートやダッシュボードの作成と管理も可能です。 


| 管理者 | 管理者 | 作成者のすべての機能だけでなく、レポートの設定や、レポートタスクのシャットダウンと再起動などのすべての管理タスクも実行できます。 
|===
次の表は、各 Reporting ロールで使用できる機能を示しています。

|===


| フィーチャー（ Feature ） | 消費者 | 作成者 | 管理者 


| [ チームコンテンツ ] タブでレポートを表示します | はい。 | はい。 | はい。 


| レポートを実行する | はい。 | はい。 | はい。 


| レポートのスケジュールを設定する | はい。 | はい。 | はい。 


| 外部ファイルをアップロードします | いいえ | はい。 | はい。 


| ジョブを作成します | いいえ | はい。 | はい。 


| ストーリーを作成します | いいえ | はい。 | はい。 


| レポートを作成します | いいえ | はい。 | はい。 


| パッケージとデータモジュールを作成します | いいえ | はい。 | はい。 


| 管理タスクを実行 | いいえ | いいえ | はい。 
|===


== Reporting （ Cognos ） E メールの設定


NOTE: Cloud Insights Reporting （ Cognos アプリケーション）でユーザの E メール設定を変更した場合、それらの設定は現在のセッション _ に対してのみアクティブになります。Cognos からログアウトして再度ログインすると、 E メールの設定がリセットされます。



== 既存のお客様にとって重要な注意事項です

Cloud Insights with Reporting を初めてお使いになる方へようこそ。レポートの利用を開始するために、これ以上何もする必要はありません。

現在 Premium Edition をお使いの場合、 SSO はお使いの環境で自動的に有効になりません。SSO を有効にすると、 Reporting Portal （ Cognos ）の管理者ユーザが存在しなくなります。つまり '_My Content_ フォルダにあるすべてのレポートが削除され '_Team Content_ で再インストールまたは再作成する必要がありますまた、 SSO を有効にしたあとにスケジュールされたレポートを設定する必要があります。



=== SSO を有効にするために既存の環境を準備するには、どのような手順を実行する必要がありますか。

レポートを確実に保持するには、次の手順を使用して、 _My Content_to _Team Content_ からすべてのレポートを移行します。この作業は、環境で SSO を有効にする前に行う必要があります。

. _Team Content_ に新しいフォルダを作成します
+
.. 複数のユーザーが作成されている場合は、重複した名前でレポートを上書きしないように、ユーザーごとに個別のフォルダを作成してください


. マイコンテンツ _ に移動します
. 保持するすべてのレポートを選択します。
. メニューの右上隅で、 [ コピーまたは移動 ] を選択します。
. _Team Content_ で新しく作成したフォルダに移動します
. [ コピー先 ] または [ 移動先 ] ボタンを使用して、新しく作成したフォルダにレポートを貼り付けます
. Cognos で SSO を有効にしたら、アカウントの作成に使用した E メールアドレスで Cloud Insights にログインします。
. Cognos 内の _Team Content_folder に移動し、以前に保存したレポートを _My Content_ にコピーまたは移動します。

