---
sidebar: sidebar 
permalink: task-planning-your-config.html 
keywords: license, disk, ebs, storage, size, write speed, volume usage, ec2, capacity, limit, configurations, virtual machine, vm, regions, supported disks, disk types, general purpose, gp2 provisioned IOPS, piops, throughput optimized, cold, SSD, HDD, st1, use profile, thin provisioning, deduplication, compression, shared instance, dedicated instance, write speed, high write speed, normal write speed, network information, worksheet, limit, limits, storage limits, volume limit, aggregate limit, maximum volume size, maximum aggregate size, supported instances, instances, instances supported, supported ec2 instances, supported instance, aws outpost, outpost, outposts, deploy in outpost, deploy in aws outpost 
summary: AWS に Cloud Volumes ONTAP を導入する場合は、ワークロードの要件に応じて事前設定されたシステムを選択するか、または独自の設定を作成できます。独自の設定を選択する場合は、使用可能なオプションを理解しておく必要があります。 
---
= AWSでCloud Volumes ONTAP 構成を計画
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
AWS に Cloud Volumes ONTAP を導入する場合は、ワークロードの要件に応じて事前設定されたシステムを選択するか、または独自の設定を作成できます。独自の設定を選択する場合は、使用可能なオプションを理解しておく必要があります。



== Cloud Volumes ONTAP ライセンスを選択します

Cloud Volumes ONTAP には、いくつかのライセンスオプションがあります。それぞれのオプションで、ニーズに合った消費モデルを選択できます。

* link:concept-licensing.html["Cloud Volumes ONTAP のライセンスオプションについて説明します"]
* link:task-set-up-licensing-aws.html["ライセンスの設定方法について説明します"]




== サポートされているリージョンを選択します

Cloud Volumes ONTAP はほとんどの AWS リージョンでサポートされています。 https://cloud.netapp.com/cloud-volumes-global-regions["サポートされているリージョンの完全なリストを表示します"^]。

新しい AWS リージョンは、それらのリージョンでリソースを作成および管理する前に有効にする必要があります。 https://docs.aws.amazon.com/general/latest/gr/rande-manage.html["リージョンを有効にする方法について説明します"^]。



== サポートされているインスタンスを選択します

Cloud Volumes ONTAP では、選択したライセンスタイプに応じて、複数のインスタンスタイプがサポートされます。

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-aws.html["AWS で Cloud Volumes ONTAP がサポートされる構成"^]



== ストレージの制限を確認

Cloud Volumes ONTAP システムの未フォーマット時の容量制限は、ライセンスに関連付けられています。追加の制限は、アグリゲートとボリュームのサイズに影響します。設定を計画する際には、これらの制限に注意する必要があります。

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-limits-aws.html["AWS での Cloud Volumes ONTAP のストレージの制限"^]



== AWSでシステムのサイズを設定します

Cloud Volumes ONTAP システムのサイジングを行うことで、パフォーマンスと容量の要件を満たすのに役立ちます。インスタンスタイプ、ディスクタイプ、およびディスクサイズを選択する際には、次の点に注意する必要があります。

インスタンスタイプ::
+
--
* ワークロードの要件を、各 EC2 インスタンスタイプの最大スループットと IOPS に合わせます。
* 複数のユーザが同時にシステムに書き込む場合は、要求を管理するのに十分な CPU を備えたインスタンスタイプを選択します。
* 読み取りが多いアプリケーションがある場合は、十分な RAM が搭載されたシステムを選択します。
+
** https://aws.amazon.com/ec2/instance-types/["AWS ドキュメント：「 Amazon EC2 Instance Types"^]
** https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSOptimized.html["AWS のドキュメント：「 Amazon EBS – Optimized instances"^]




--
EBS ディスクタイプ:: EBS ディスクタイプの違いは次のとおりです。EBS ディスクのユースケースの詳細については、を参照してください http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html["AWS ドキュメント：「 EBS Volume Types"^]。
+
--
* _General Purpose SSD （ GP3 ） _ ディスクは、幅広いワークロードに対してコストとパフォーマンスのバランスを取る最も低コストの SSD です。パフォーマンスは、 IOPS とスループットを基準に定義されます。GP3 ディスクは Cloud Volumes ONTAP 9.7 以降でサポートされています。
+
GP3ディスクを選択すると、選択したディスクサイズに基づいて、gp2ディスクに相当するパフォーマンスを提供するデフォルトのIOPSとスループットの値がBlueXPによって設定されます。この値を増やすと、コストを高くしてもパフォーマンスを向上させることができますが、パフォーマンスが低下する可能性があるため、値を小さくすることはできません。つまり、デフォルト値をそのまま使用するか、値を大きくします。低くしないでください。 https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volume-types.html#gp3-ebs-volume-type["GP3 ディスクとそのパフォーマンスについては、こちらをご覧ください"^]。

+
Cloud Volumes ONTAP は、GP3ディスクを使用したAmazon EBS Elastic Volumes機能をサポートしています。 link:concept-aws-elastic-volumes.html["Elastic Volumesのサポートに関する詳細情報"]。

* _ 汎用 SSD （ gp2 ） _ ディスクは、幅広いワークロードに対してコストとパフォーマンスのバランスを取ります。パフォーマンスは IOPS の観点から定義されます。
* _Provisioned IOPS SSD （ io1 ） _disks は、コストが高くても最高のパフォーマンスが求められる重要なアプリケーション用です。
+
Cloud Volumes ONTAP では、io1ディスクを使用したAmazon EBS Elastic Volumes機能がサポートされています。 link:concept-aws-elastic-volumes.html["Elastic Volumesのサポートに関する詳細情報"]。

* _Throughput Optimized HDD （ st1 ） _disks は、高速で安定したスループットを必要とする、アクセス頻度の高いワークロード用です。価格は低くなります。
+

NOTE: スループット最適化 HDD （ st1 ）を使用している場合、オブジェクトストレージへのデータの階層化は推奨されません。



--
EBS ディスクサイズ:: をサポートしない構成を選択した場合 link:concept-aws-elastic-volumes.html["Amazon EBS Elastic Volumes機能"]を選択した場合、Cloud Volumes ONTAP システムの起動時に初期ディスクサイズを選択する必要があります。その後、次の操作を実行できます link:concept-storage-management.html["システムの容量をBlueXPが管理できるようにします"]必要に応じて link:task-create-aggregates.html["アグリゲートの作成は自分で行います"]、次の点に注意してください。
+
--
* アグリゲート内のディスクはすべて同じサイズである必要があります。
* EBS ディスクのパフォーマンスはディスクサイズに依存します。サイズによって、 SSD ディスクのベースライン IOPS と最大バースト期間、および HDD ディスクのベースラインスループットとバーストスループットが決まります。
* 最終的には、必要なパフォーマンスを継続的に提供するディスクサイズを選択する必要があります。
* 4 TiB のディスクを 6 台使用するなど、大容量のディスクを選択した場合でも、 EC2 インスタンスの帯域幅が制限に達する可能性があるため、すべての IOPS が得られないことがあります。
+
EBS ディスクのパフォーマンスの詳細については、を参照してください http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html["AWS ドキュメント：「 EBS Volume Types"^]。

+
前述したように、ディスクサイズの選択は、Amazon EBS Elastic Volumes機能をサポートするCloud Volumes ONTAP 構成ではサポートされていません。 link:concept-aws-elastic-volumes.html["Elastic Volumesのサポートに関する詳細情報"]。



--




== デフォルトのシステムディスクを表示します

ユーザデータ用のストレージに加えて、BlueXPはCloud Volumes ONTAP システムデータ（ブートデータ、ルートデータ、コアデータ、NVRAM）用のクラウドストレージも購入します。計画を立てる場合は、 Cloud Volumes ONTAP を導入する前にこれらの詳細を確認すると役立つ場合があります。

link:reference-default-configs.html#aws["AWS で Cloud Volumes ONTAP システムデータのデフォルトディスクを表示する"]。


TIP: コネクタにはシステムディスクも必要です。 https://docs.netapp.com/us-en/bluexp-setup-admin/reference-connector-default-config.html["コネクタのデフォルト設定に関する詳細を表示します"^]。



== AWSアウトポストにCloud Volumes ONTAP を導入する準備をします

AWS Outpost を使用している場合は、 Working Environment ウィザードで Outpost VPC を選択して、その Outpost に Cloud Volumes ONTAP を導入できます。エクスペリエンスは、 AWS に存在する他の VPC と同じです。最初に、 AWS Outpost にコネクタを導入する必要があります。

指摘すべき制限事項はいくつかあります。

* でサポートされるのはシングルノードの Cloud Volumes ONTAP システムのみです 今回は
* Cloud Volumes で使用できる EC2 インスタンス ONTAP は、 Outpost で利用できる機能に限定されています
* 現時点では、汎用 SSD （ gp2 ）のみがサポートされます




== ネットワーク情報を収集

AWS で Cloud Volumes ONTAP を起動する場合は、 VPC ネットワークの詳細を指定する必要があります。ワークシートを使用して、管理者から情報を収集できます。



=== 単一のAZにおける単一のノードまたはHAペア

[cols="30,70"]
|===
| AWS 情報 | あなたの価値 


| 地域 |  


| vPC |  


| サブネット |  


| セキュリティグループ（独自のグループを使用している場合） |  
|===


=== 複数のAZにまたがるHAペアを作成します

[cols="30,70"]
|===
| AWS 情報 | あなたの価値 


| 地域 |  


| vPC |  


| セキュリティグループ（独自のグループを使用している場合） |  


| ノード 1 の可用性ゾーン |  


| ノード 1 のサブネット |  


| ノード2のアベイラビリティゾーン |  


| ノード2のサブネット |  


| メディエータ可用性ゾーン |  


| メディエータサブネット |  


| メディエータのキーペア |  


| クラスタ管理ポートのフローティング IP アドレス |  


| ノード 1 のデータの浮動 IP アドレス |  


| ノード2のデータのフローティングIPアドレス |  


| フローティング IP アドレスのルートテーブル |  
|===


== 書き込み速度を選択します

BlueXPでは、Cloud Volumes ONTAP の書き込み速度設定を選択できます。書き込み速度を選択する前に、高速書き込みを使用する場合の標準設定と高設定の違い、およびリスクと推奨事項を理解しておく必要があります。 link:concept-write-speed.html["書き込み速度の詳細については、こちらをご覧ください。"]。



== ボリュームの使用プロファイルを選択してください

ONTAP には、必要なストレージの合計容量を削減できるストレージ効率化機能がいくつか搭載されています。BlueXPでボリュームを作成するときに、これらの機能を有効にするプロファイル、または無効にするプロファイルを選択できます。これらの機能の詳細については、使用するプロファイルを決定する際に役立ちます。

NetApp Storage Efficiency 機能には、次のようなメリットがあります。

シンプロビジョニング:: 物理ストレージプールよりも多くの論理ストレージをホストまたはユーザに提供します。ストレージスペースは、事前にストレージスペースを割り当てる代わりに、データの書き込み時に各ボリュームに動的に割り当てられます。
重複排除:: 同一のデータブロックを検索し、単一の共有ブロックへの参照に置き換えることで、効率を向上します。この手法では、同じボリュームに存在するデータの冗長ブロックを排除することで、ストレージ容量の要件を軽減します。
圧縮:: プライマリ、セカンダリ、アーカイブストレージ上のボリューム内のデータを圧縮することで、データの格納に必要な物理容量を削減します。

