---
sidebar: sidebar 
permalink: task_dc_na_astra_data_store.html 
summary: ネットアップの Astra データストアを設定 
keywords: data collector, queries, create, astra, data, store, 
---
= NetApp Astra データコレクタ
:allow-uri-read: 


[role="lead"]
このデータコレクタは、単一の Astra データストアクラスタのインベントリデータとパフォーマンスデータを取得します。データコレクタに加えて、 Monitoring Operator は _Telegraf _ を設定して、高度なメトリックと _Fluent bit_to 収集ログを収集します。


TIP: 以下のインストール手順と追加情報は、 Astra データストアのドキュメントにも記載されています。link:https://docs.netapp.com/us-en/astra-data-store/use/monitor-with-cloud-insights.html["Cloud Insights で指標を監視"]
link:https://docs.netapp.com/us-en/astra-data-store/get-started/quick-start.html["Astra データストアのクイックスタート"]



== 用語集

Cloud Insights は、このデータコレクタからインベントリデータとパフォーマンスデータを取得します。取得したアセットのタイプごとに、そのアセットに使用される最も一般的な用語が表示されます。このデータコレクタを表示またはトラブルシューティングするときは、次の用語に注意してください。

[cols="2*"]
|===
| ベンダー / モデルの用語 | Cloud Insights の用語 


| AstraDSVolume | 内部ボリューム 


| AstraDSNodeInfo.status.drives | ディスク 


| AstraDSNodeInfo | ストレージノード 


| AstraDSExportPolicy の順にクリックします | 共有 / 共有イニシエータ 


| AstraDSCluster | ストレージ 
|===


== 要件

* NetApp Monitoring Operator は、 Astra データストアを使用する Kubernetes クラスタにインストールする必要があります。Astra Data Store のインストール時にインストールされなかった場合は、 Astra Data Store のインストール手順に従って、モニタリングオペレータをインストールしてください。
* _kubectl-astras_kubectl プラグインをインストールする必要がありますインストールされていない場合は、 Astra Data Store のインストール手順に従って、 _kubectl-astrs_binary をインストールしてください。
* 利用可能なコマンドは、 _ awk 、 curl 、 grep 、および jq_ です。




== インストール

インストールスクリプトの指示に従って、 Astra Data Store データコレクタをインストールします。画面の指示に従います。インストールが完了するまでに数分かかります。完了すると、データが Cloud Insights に表示されるまでに数分かかることがあります。

スクリプトでは、次の手順を実行します。

. API のアクセストークンを選択します。
. インストールダイアログからインストーラスクリプトをコピーし、 _cloudInsights -ads-monitoring .sh という名前のファイルとして保存します。クリップボードアイコンをクリックすると、スクリプトをクリップボードにすばやくコピーできます。
. Bash ウィンドウを開き、 _cloudin保管 場所 - ads-monitoring .sh スクリプトの場所にディレクトリを変更します。
. インストールダイアログからパーミッションコマンドブロックをコピーしますクリップボードアイコンをクリックすると、コマンドをクリップボードに簡単にコピーできます。
. Bash ウィンドウに権限のコマンドを貼り付け、 Enter キーを押します。
. インストールダイアログからインストールコマンドをコピーします。クリップボードアイコンをクリックすると、コマンドをクリップボードに簡単にコピーできます。
. Bash ウィンドウに install コマンドを貼り付けます。
. 「 <Kubernetes の IP > 」を Kubernetes API サーバの IP アドレスに置き換えます。
. <Kubernetes トークン > を Kubernetes API トークンに置き換えます。
. Enter キーを押します。
+
インストーラスクリプトは、 * Monitoring Operator がインストールされ、設定されていることを確認します。* Fluent ビットを設定します。* Tegraf を設定します。* Acquisition Unit をインストールします。* Acquisition Unit を起動したら、 Astra Data Store コレクタをインストール

. 完了設定 _ をクリックします。


エラーが原因でインストーラスクリプトが終了した場合は、エラーが解決したら再実行できます。デフォルトの設定を使用しない環境の場合、インストーラスクリプトでは、 Monitoring Operator 名前空間や Kubernetes API サーバポートなどの追加のパラメータがサポートされます。使用可能なオプションの一覧を以下に示します。



=== インストーラのスクリプトオプション：

Cloud Insights ドメイン名と選択した API アクセスキーは、ダウンロード時にインストーラスクリプトに組み込まれます。

....
$ ./cloudinsights-ads-monitoring.sh -h
USAGE: cloudinsights-ads-monitoring.sh [OPTIONS]
Configure monitoring of Astra Data Store by Cloud Insights.
OPTIONS:
 -h                      Display this help message.
 -d ci_domain_name       Cloud Insights tenant domain name.
 -i kubernetes_ip        Kubernetes API server IP address.
 -k ci_api_key           Cloud Insights API Access Key.
 -n namespace            Namespace for monitoring components. (default: netapp-monitoring)
 -p kubernetes_port      Kubernetes API server port. (default: 6443)
 -r root_pv_dir          Create 3 Persistent Volumes in this directory for the Acquisition Unit.
                         Only specify this option if there is no Storage Provisioner installed and the PVs do not already exist.
 -s storage_class        Storage Class name for provisioning Acquisition Unit PVs. If not specified, the default storage class will be used.
 -t kubernetes_token     Kubernetes API server token.
....


== トラブルシューティング

このデータコレクタで問題が発生した場合の対処方法を次に示します。



==== Astra データストアデータコレクタ

[cols="2*"]
|===
| 問題 | 次の操作を実行します 


| 「 Unauthorized 」というメッセージが表示されます | Kubernetes API トークンに、 _astrads.netapp.io_ apiGroup 内の API を呼び出す権限があることを確認します 


| 不明なホスト : astrs-metric-service-astras-system.svc.cluster.local : 名前またはサービスが不明です | ADS Kubernetes クラスタ内で実行されている Acquisition Unit ポッドにコレクタがインストールされていることを確認します。astrs-metric-service が astrs-system 名前空間を実行していることを確認します。 
|===


==== インストールスクリプト

[cols="2*"]
|===
| 問題 | 次の操作を実行します 


| 名前空間で監視演算子が実行されていません。 | Astra Data Store のインストール手順に従ってインストールします 


| 300 秒後に Acquisition Unit ポッドが起動しませんでした。 | Acquisition Unit ポッドの名前を取得します。 kubectl get pod -- namespace NetApp-monitoring | grep "au-pPOD " Check the pod events for errors ： kubectl describe pod --namespace NetApp-monitoring <pod name> 


| Acquisition Unit のインストールが 900 秒経っても完了しません | Acquisition Unit ポッドの名前を取得します。 kubectl get pod -- namespace NetApp-monitoring | grep "au-pPOD " Check the pod logs for errors ： kubectl logs -- namespace netapp -monitoring <pod _name> エラーがなく、ログの末尾に「 Main-Acquisition is up and running ！」というメッセージが表示されている場合、インストールは成功しましたが、想定よりも長くなりました。インストールスクリプトを再実行します。 


| Cloud Insights から Acquisition Unit ID を取得できませんでした | Cloud Insights に Acquisition Unit が表示されることを確認します。Admin > Data Collectors に移動し、 Acquisition Unit タブをクリックします。Cloud Insights API キーに Acquisition Unit の権限があることを確認します。 
|===
この Data Collector の追加情報は、から入手できます link:concept_requesting_support.html["サポート"] ページまたはを参照してください link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector サポートマトリックス"]。
