---
sidebar: sidebar 
permalink: task_dc_na_eseries.html 
keywords: data collector, ontap, clustered ontap 
summary: NetApp E シリーズのデータコレクタの設定 
---
= NetApp E シリーズのデータコレクタ


[role="lead"]
NetApp E シリーズデータコレクタは、インベントリとパフォーマンスのデータを収集します。コレクタは、同じ設定を使用して同じデータを報告するファームウェア 7.x 以上をサポートしています。



== 用語集

Cloud Insight では、 NetApp E シリーズデータコレクタから次のインベントリ情報を取得します。取得したアセットのタイプごとに、そのアセットに使用される最も一般的な用語が表示されます。このデータコレクタを表示またはトラブルシューティングするときは、次の用語に注意してください。

[cols="2*"]
|===
| ベンダー / モデルの用語 | Cloud Insights の用語 


| ディスク | ディスク 


| ボリュームグループ | ディスクグループ 


| ストレージアレイ | ストレージ 


| コントローラ | ストレージノード 


| ボリュームグループ | ストレージプール 


| ボリューム | ボリューム 
|===
注：これらは一般的な用語の対応のみを示したものであり、このデータコレクタのすべてのケースを表しているわけではありません。



== E シリーズの用語（ランディングページ）

NetApp E シリーズのアセットランディングページにあるオブジェクトや参考資料に関連する用語を次に示します。これらの用語の多くは、他のデータコレクタにも適用されます。



=== ストレージ

* Model –デバイスのモデル名。
* Vendor ：新しいデータソースを設定する場合に表示されるベンダー名と同じです
* Serial Number –アレイのシリアル番号。NetApp clustered Data ONTAP などのクラスタアーキテクチャストレージシステムでは、このシリアル番号は個々の「ストレージノード」のシリアル番号よりも便利でない場合があります
* IP –一般に、データソースで設定されている IP またはホスト名です
* マイクロコードバージョン–ファームウェア
* raw 容量–システム内のすべての物理ディスクの合計 2 進数で、役割に関係なく加算されます
* レイテンシ–読み取りと書き込みの両方について、ワークロードが直面しているホストの状況が表示されます。Cloud Insights がこの値を直接調達するのが理想的ですが、これは多くの場合ではありません。Cloud Insights は、このアップを提供するアレイの代わりに、通常、個々のボリュームの統計情報から導出される IOPS 加重計算を実行します。
* スループット–アレイのホスト側のスループットの合計理想的にはアレイから直接ソースを取得し、使用できない場合は、 Cloud Insights がボリュームのスループットを合計してこの値を算出します
* 管理–デバイスの管理インターフェイスのハイパーリンクが含まれている可能性があります。インベントリレポートの一部として、 Cloud Insights データソースによってプログラムによって作成されます




=== ストレージプール

* storage –このプールのストレージアレイの場所。必須
* Type –可能性のリストから説明的な値を入力します。最も一般的な構成は、「シン・プロビジョニング」または「 RAID グループ」です。
* ノード：プールが特定のストレージノードに属するようなストレージアレイのアーキテクチャの場合、その名前は、そのストレージアレイのランディングページへのハイパーリンクとして表示されます
* Flash Pool を使用します。値はありますか、いいえです
* 冗長性– RAID レベルまたは保護方式。E シリーズでは、 DDP プールの場合は「 RAID 7 」と報告されます
* 容量–使用済みの論理容量、使用可能な容量、および合計論理容量の値と、これらの要素で使用されている割合の値が表示されます。これらの値には、 E シリーズの「予約済み」容量が含まれ、 E シリーズのユーザインターフェイスで表示される値よりも数値と割合が高くなります
* オーバーコミット容量–効率化テクノロジを使用して、ストレージプールの論理容量を超えるボリュームまたは内部ボリュームの合計容量を割り当てている場合、この割合の値は 0% を超えます。
* スナップショット–スナップショット専用のセグメント領域にストレージプールアーキテクチャが容量の一部を割り当てている場合に使用されるスナップショット容量と合計容量
* 利用率–このストレージプールに容量を追加しているディスクのビジー率の最大値を示した割合。ディスク利用率にアレイのパフォーマンスとの間に大きな相関関係があるとは限りません。ホストベースのワークロードがない場合は、ディスクのリビルドや重複排除処理などが原因で、利用率が高くなる可能性があります。また、多くのアレイのレプリケーション実装では、ボリュームワークロードとして表示されずにディスク使用率が向上する場合があります。
* IOPS –このストレージプールに容量の要因となっているすべてのディスクの合計 IOPS 。特定のプラットフォームのディスク IOPS がない場合、この値は、このストレージプールにあるすべてのボリュームのボリューム IOPS の合計から取得されます
* Throughput –このストレージプールの容量の要因となっているすべてのディスクの合計スループット。特定のプラットフォームでディスクスループットを使用できない場合は、このストレージプールに配置されているすべてのボリュームの合計ボリューム数がこの値に基づいて算出されます




=== ストレージノード

* Storage –このノードが属するストレージアレイ。必須
* HA パートナー–通常、一方のノードだけにフェイルオーバーするプラットフォームでは、この画面が表示されます
* State –ノードの健常性。アレイが正常な状態でデータソースでインベントリを作成できる場合にのみ使用できます
* model - ノードのモデル名
* Version ：デバイスのバージョン名。
* シリアル番号–ノードのシリアル番号
* メモリ–ベース 2 のメモリがあればそれ
* 利用率–通常は CPU 利用率番号、または NetApp ONTAP の場合はコントローラに負荷がかかる指標。現在、 NetApp E シリーズでは利用率を利用できません
* IOPS –このコントローラのホスト主導の IOPS を表す数値。理想的なソースはアレイから直接取得され、使用できない場合は、このノードにのみ所属するボリュームのすべての IOPS を合計して算出されます。
* Latency –このコントローラのホストのレイテンシまたは応答時間を表す数値。使用できない場合はアレイから直接ソースを取得し、このノードにのみ所属するボリュームから IOPS の重み付き計算を実行することを推奨します。
* Throughput –このコントローラのホストで実行されるスループットを示す数値です。理想的なソースはアレイから直接取得され、使用できない場合は、このノードにのみ所属するボリュームのすべてのスループットを合計して算出されます。
* プロセッサ– CPU 数




== 要件

* アレイの各コントローラの IP アドレス
* ポート要件 2463




== 設定

[cols="2*"]
|===
| フィールド | 説明 


| アレイ SANtricity コントローラの IP をカンマで区切ったリスト | アレイコントローラの IP アドレスまたは完全修飾ドメイン名 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 説明 


| インベントリポーリング間隔（分） | デフォルトは 30 分です 


| パフォーマンスポーリング間隔（最大 3600 秒） | デフォルト値は 300 秒です 
|===


== トラブルシューティング

この Data Collector の追加情報は、から入手できます link:concept_requesting_support.html["サポート"] ページまたはを参照してください link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector サポートマトリックス"]。
