---
sidebar: sidebar 
permalink: task_dc_ibm_powervm.html 
keywords: IBM, powerVM, 
summary: IBM PowerVM データコレクタを設定しています。 
---
= IBM PowerVM データコレクタの設定
:allow-uri-read: 


[role="lead"]
IBM PowerVM （ SSH ）データコレクタは、ハードウェア管理コンソール（ HMC ）で管理される IBM POWER ハードウェアインスタンスで実行されている仮想パーティションに関する情報を収集するために使用されます。



== 用語集

Cloud Insights は、 IBM POWER ハードウェアインスタンスで実行されている仮想パーティションからインベントリ情報を取得します。取得したアセットのタイプごとに、そのアセットに使用される最も一般的な用語が表示されます。このデータコレクタを表示またはトラブルシューティングするときは、次の用語に注意してください。

[cols="2*"]
|===
| ベンダー / モデルの用語 | Cloud Insights の用語 


| hdisk | 仮想ディスク 


| Managed System の略 | ホスト 


| LPAR 、 VIO サーバ | 仮想マシン 


| ボリュームグループ | データストア 


| 物理ボリューム | LUN 
|===
注：これらは一般的な用語の対応のみを示したものであり、このデータコレクタのすべてのケースを表しているわけではありません。



== 要件

このデータコレクタを設定して使用するには、次の要件を満たしている必要があります。

* ハードウェア管理コンソール（ HMC ）の IP アドレス
* SSH を使用してハードウェア管理コンソール（ HMC ）にアクセスするためのユーザ名とパスワード
* ポート要件は SSH-22 です
* すべての管理システムおよび論理パーティションセキュリティドメインに対する表示権限
+
ユーザには、 HMC の設定に対する表示権限も必要であり、 HMC コンソールセキュリティグループの VPD 情報を収集できる必要があります。ユーザーは、論理パーティションセキュリティグループの Virtual IO Server コマンドへのアクセスも許可されている必要があります。オペレータのロールから開始し、すべてのロールを削除することを推奨します。HMC の読み取り専用ユーザには、 AIX ホストでプロキシされたコマンドを実行する権限はありません。

* IBM のベストプラクティスは、 2 台以上の HMI でデバイスを監視することです。これにより、原因 OnCommand Insight で重複したデバイスが報告される場合があるため、このデータコレクタの詳細設定の [ デバイスを除外する ] リストに冗長デバイスを追加することを強くお勧めします。




== 設定

[cols="2*"]
|===
| フィールド | 説明 


| ハードウェア管理コンソール（ HMC ）の IP アドレス | PowerVM ハードウェア管理コンソールの IP アドレスまたは完全修飾ドメイン名 


| HMC ユーザ | ハードウェア管理コンソールのユーザ名 


| パスワード | ハードウェア管理コンソールのパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 説明 


| インベントリポーリング間隔（分） | インベントリのポーリング間隔。デフォルトは 20 分です。 


| SSH ポート | PowerVM への SSH に使用するポート 


| パスワード | ハードウェア管理コンソールのパスワード 


| 再試行回数 | インベントリの再試行回数 


| デバイスを除外します | 対象から除外するデバイスの ID または表示名をカンマで区切ったリスト 
|===


== トラブルシューティング

この Data Collector の追加情報は、から入手できます link:concept_requesting_support.html["サポート"] ページまたはを参照してください link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector サポートマトリックス"]。
