---
sidebar: sidebar 
permalink: task_config_cs_amazon_fsx.html 
keywords: Cloud, Storage, AWS, Fsx 
summary: Cloud Secure では、データコレクタを使用して、デバイスからファイルとユーザのアクセスデータを収集します。 
---
= NetApp ONTAP 構成用の Amazon FSX
:allow-uri-read: 


[role="lead"]
このデータコレクタは、 NetApp ONTAP 対応の Amazon FSX からファイルとユーザのアクセスデータを収集します。このデータコレクタは、 Cloud Insights サービスリージョン全体で段階的に利用可能になります。Cloud Insights 環境にこのコレクタのアイコンが表示されない場合は、営業担当者にお問い合わせください。



=== Agent Machine Configuration の略

Cloud Secure エージェントとして使用するマシンを設定するには、次の手順を実行します。

. AWS コンソールにログインし、 EC2-Instances ページに移動して Launch instance を選択します。
. に記載されているバージョンに応じて、 RHEL または CentOS AMI を選択します link:concept_cs_agent_requirements.html["要件"]。
. Amazon FSX for NetApp ONTAP インスタンスが存在する VPC とサブネットに Agent ボックスを作成します。
+
または、ネットアップ ONTAP VPC の Amazon FSX に接続された VPC 内にエージェントボックスを配置する必要があります。

+
エージェントと Amazon FSX for NetApp ONTAP の間に双方向の通信が確立されていることを確認します。

. 割り当てられたリソースとして、 t2.xlarge （ 4 vCPU と 16 GB RAM ）を選択します。
+
.. EC2 インスタンスを作成します。


. YUM パッケージマネージャを使用して、必要な Linux パッケージをインストールします。
+
.. wget および unzip のネイティブ Linux パッケージをインストールします。






=== Cloud Secure エージェントをインストールします

. Cloud Insights 環境に管理者またはアカウント所有者としてログインします。
. Cloud Secure Admin > Data Collectors に移動し、 Agents タブをクリックします。
. + Agent をクリックし、ターゲットプラットフォームとして RHEL を指定します。
. [ エージェントインストール ] コマンドをコピーします。
. ログインしている RHEL EC2 インスタンスに Agent Installation コマンドを貼り付けます。
+
これにより、すべてのエージェント前提条件が満たされていれば、 Cloud Secure エージェントがインストールされます。



詳細な手順については、 Cloud Secure を参照してください link:task_cs_add_agent.html["エージェントのインストール"] ページ
