---
sidebar: sidebar 
permalink: task_device_resolution_preferences.html 
keywords: Automatic, AR, AHR, Host, automatic device resolution, FC, Identify 
summary:  
---
= [ 環境設定 ] タブでオプションを設定します


[role="lead"]
デバイス解決のプリファレンスタブでは、自動解決スケジュールの作成、識別情報を含めるストレージベンダーやテープベンダーの指定、および DNS 検索オプションの設定を行うことができます。



=== 自動解決スケジュール

自動デバイス解決を実行するスケジュールを指定できます。

|===


| オプション | 説明 


| 間隔 | 曜日、時間、または分単位で自動デバイス解決を実行する場合は、このオプションを使用します。 


| 毎日 | このオプションは、自動デバイス解決を特定の時刻に毎日実行する場合に使用します。 


| 手動で実行する | このオプションは、自動デバイス解決を手動でのみ実行する場合に使用します。 


| 環境が変化するたびに | このオプションは、環境に変更があったときに自動デバイス解決を実行する場合に使用します。 
|===
manually_manually__ を指定すると、毎晩の自動デバイス解決が無効になります。



=== DNS の処理オプション

DNS の処理オプションでは、次の機能を選択できます。

* DNS ルックアップの結果の処理を有効にすると、解決されたデバイスに付加する DNS 名のリストを追加できます。
* Auto resolution of IPs ：を選択すると、 NFS 共有にアクセスする iSCSI イニシエータおよびホストについて、 DNS ルックアップを使用した自動ホスト解決を有効にできます。指定しない場合は、 FC ベースの解決のみが実行されます。
* ホスト名にアンダースコアを使用できるようにすることも、標準のポートエイリアスの代わりに「接続先」のエイリアスを使用することもできます。




=== ストレージやテープの特定のベンダーを含めるか、除外します

ストレージやテープの特定のベンダーを自動解決の対象に含めたり除外したりできます。レガシーホストとなり、新しい環境から除外する必要があることがわかっているホストがある場合などは、特定のベンダーを除外することができます。除外したベンダーを再度追加することもできます。


NOTE: テープのデバイス解決ルールは、 WWN のベンダーがテープ専用に設定されている WWN でのみ機能します。ベンダーの環境設定では、その WWN のベンダーがテープ専用に設定されています。

次も参照してください。 link:concept_device_resolution_regex_examples.html["正規表現の例"]
