---
sidebar: sidebar 
permalink: task_dc_na_amazon_fsx.html 
keywords: 'data collector, stout, fsx, fsx-netapp, Amazon, AWS, cluster, volume, share, LUN"' 
summary: NetApp ONTAP Data Collector 向けの Amazon FSX 
---
= NetApp ONTAP データコレクタ用の Amazon FSX


[role="lead"]
このデータコレクタは、 Amazon FSX for NetApp ONTAP からインベントリデータとパフォーマンスデータを取得します。このデータコレクタは、 Cloud Insights サービスリージョン全体で段階的に利用可能になります。Cloud Insights 環境にこのコレクタのアイコンが表示されない場合は、営業担当者にお問い合わせください。



== 用語集

Cloud Insights は、 FSx-NetApp データコレクタからインベントリデータとパフォーマンスデータを取得します。取得したアセットのタイプごとに、そのアセットに使用される最も一般的な用語が表示されます。このデータコレクタを表示またはトラブルシューティングするときは、次の用語に注意してください。

[cols="2*"]
|===
| ベンダー / モデルの用語 | Cloud Insights の用語 


| クラスタ | ストレージ 


| LUN | ボリューム 


| ボリューム | 内部ボリューム 
|===


== FSX - ネットアップの用語

FSx-NetApp ストレージアセットランディングページにあるオブジェクトや参考資料に関連する用語を次に示します。これらの用語の多くは、他のデータコレクタにも適用されます。



=== ストレージ

* model –このクラスタ内で一意のディスクリートモデル名をカンマで区切って指定します。
* ベンダー– AWS （ Hitachi ）
* Serial Number –アレイのシリアル番号。
* IP –一般に、データソースで設定されている IP またはホスト名です。
* raw 容量–システム内のすべての物理ディスクの合計 2 進数で、役割に関係なく加算されます。
* レイテンシ–読み取りと書き込みの両方について、ワークロードが直面しているホストの状況が表示されます。Cloud Insights がこの値を直接調達するのが理想的ですが、これは多くの場合ではありません。Cloud Insights は、このアップを提供するアレイの代わりに、通常、個々の内部ボリュームの統計情報から導出される IOPS 加重計算を実行します。
* スループット–内部ボリュームから集約されたもの。管理–デバイスの管理インターフェイスのハイパーリンクが含まれている可能性があります。Cloud Insights データソースによって、インベントリレポートの一部としてプログラムによって作成されます。




=== ストレージプール

* storage –このプールのストレージアレイの場所。必須。
* Type –可能性のリストから説明的な値を入力します。最も一般的な構成は、「集約」または「 RAID グループ」です。
* Flash Pool を使用–値はあり / いいえ–この SATA / SAS ベースのプールでは、 SSD をキャッシュ高速化に使用していますか？
* 冗長性– RAID レベルまたは保護方式。raid_dp はデュアルパリティ、 raid_dp はトリプルパリティです。
* 容量–使用済みの論理容量、使用可能な容量、および合計論理容量の値と、これらの要素で使用されている割合の値が表示されます。
* オーバーコミット容量–効率化テクノロジを使用して、ストレージプールの論理容量よりも大きいボリュームまたは内部ボリュームの容量の合計を割り当てている場合、この割合は 0% よりも大きくなります。
* スナップショット–スナップショット専用のセグメント領域にストレージプールアーキテクチャが容量の一部を割り当てている場合に使用されるスナップショット容量と合計容量。MetroCluster 構成の ONTAP はこのような構成を示しますが、それ以外の ONTAP 構成はそうではありません。
* 利用率–このストレージプールに容量を追加しているディスクのビジー率の最大値を示した割合。ディスク利用率にアレイのパフォーマンスとの間に大きな相関関係があるとは限りません。ホストベースのワークロードがない場合は、ディスクのリビルドや重複排除処理などが原因で、利用率が高くなる可能性があります。また、多くのアレイのレプリケーション実装では、内部ボリュームやボリュームのワークロードとしては表示されずにディスク使用率が向上する場合があります。
* IOPS –このストレージプールに容量の要因となっているすべてのディスクの合計 IOPS 。Throughput –このストレージプールの容量の要因となっているすべてのディスクの合計スループット。




== 要件

このデータコレクタを設定して使用するための要件は次のとおりです。

* 読み取り専用の API 呼び出し用に設定された管理者アカウントへのアクセス権が必要です。
* アカウントの詳細には、ユーザ名とパスワードが含まれます。
* ポートの要件： 80 または 443




== 設定

[cols="2*"]
|===
| フィールド | 説明 


| ネットアップ管理 IP | ネットアップクラスタの IP アドレスまたは完全修飾ドメイン名 


| ユーザ名 | ネットアップクラスタのユーザ名 


| パスワード | ネットアップクラスタのパスワード 
|===


== トラブルシューティング

このデータコレクタで問題が発生した場合の対処方法を次に示します。



==== 在庫

[cols="2*"]
|===
| 問題 | 次の操作を実行します 


| 401 HTTP 応答または 13003 ZAPI エラーコードを受信し、 ZAPI から「 Insufficient privileges 」または「 Not authorized for this command 」が返される | ユーザ名とパスワード、およびユーザの権限と権限を確認してください。 


| ZAPI から「 cluster role is not cluster_mgmt LIF 」が返される | AU はクラスタ管理 IP と通信する必要があります。IP を確認し、必要に応じて別の IP に変更してください 


| ZAPI コマンドの再試行後に失敗する | AU でクラスタとの通信に問題があります。ネットワーク、ポート番号、および IP アドレスを確認してください。また、 AU マシンのコマンドラインからもコマンドを実行しようとします。 


| AU が HTTP 経由で ZAPI に接続できませんでした | ZAPI ポートでプレーンテキストが受け入れるかどうかを確認します。AU が SSL ソケットにプレーンテキストを送信しようとすると、通信に失敗します。 


| SSLException で通信が失敗します | AU が Filer 上のプレーンテキストポートに SSL を送信しようとしています。ZAPI ポートで SSL を受け入れるか、別のポートを使用するかを確認します。 


| その他の接続エラー： ZAPI 応答にはエラーコード 13001 、「 database is not open 」 ZAPI エラーコード 60 があり、応答に「 API did not finished on time 」という応答が含まれています。 ZAPI エラーコード 14007 では「 initialize_session() returned NULL environment 」が返され、応答に「 Node is not healthy 」が含まれます。 | ネットワーク、ポート番号、および IP アドレスを確認してください。また、 AU マシンのコマンドラインからもコマンドを実行しようとします。 
|===
追加情報はから入手できます link:concept_requesting_support.html["サポート"] ページまたはを参照してください link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector サポートマトリックス"]。
