---
sidebar: sidebar 
permalink: task_dc_nutanix.html 
keywords: data collector, Nutanix, NX Series 
summary: Nutanix のデータコレクタの設定 
---
= Nutanix NX データコレクタ


[role="lead"]
Cloud Insights は、 Nutanix データコレクタを使用して、 Nutanix NX ストレージシステムのインベントリとパフォーマンスのデータを検出します。



== 用語集

Cloud Insights は、 Nutanix データコレクタから次のインベントリ情報を取得します。Cloud Insights では、取得したアセットのタイプごとに、そのアセットに使用される最も一般的な用語が表示されます。このデータコレクタを表示またはトラブルシューティングするときは、次の用語に注意してください。

[cols="2*"]
|===
| ベンダー / モデルの用語 | Cloud Insights の用語 


| ストレージプール | ストレージプール 


| Nutanix コンテナ | 内部ボリューム 


| Nutanix コンテナ | ファイル共有 


| NFS 共有 | 共有 
|===
注：これらは一般的な用語の対応のみを示したものであり、このデータコレクタのすべてのケースを表しているわけではありません。



== 要件

* クラスタの外部データサービスの IP アドレス
* volume_groups が使用されていないかぎり、読み取り専用のユーザ名とパスワード。この場合は、 Admin ユーザ名とパスワードが必要です
* ポート要件： HTTPS 443




== 設定

[cols="2*"]
|===
| フィールド | 説明 


| プリズム外部 IP アドレス | クラスタの外部データサービスの IP アドレス 


| ユーザ名 | 管理者アカウントのユーザ名 


| パスワード | 管理者アカウントのパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 説明 


| TCP ポート | Nutanix アレイへの接続に使用する TCP ポート。デフォルトは 9440. です。 


| インベントリのポーリング間隔（分） | インベントリのポーリング間隔。デフォルトは 60 分です。 


| パフォーマンスのポーリング間隔（秒） | パフォーマンスのポーリング間隔デフォルトは 300 秒です。 
|===


== トラブルシューティング

この Data Collector の追加情報は、から入手できます link:concept_requesting_support.html["サポート"] ページまたはを参照してください link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector サポートマトリックス"]。
