---
sidebar: sidebar 
permalink: task_create_annotation_rules.html 
summary: アノテーションルールを作成して、複数のアセットにアノテーションを自動的に適用します。 
---
= アノテーションルールの作成
:allow-uri-read: 


[role="lead"]
アノテーションルールを使用すると、定義した条件に基づいて複数のアセットにアノテーションを自動的に適用できます。それらのルールに基づいて、アセットにアノテーションが割り当てられます。 Cloud Insights個々のアセットページで手動で設定したアノテーションは、 Cloud Insight でアノテーションルールが評価されるときにルールベースのアノテーションよりも優先されます。

アノテーションルールのクエリを作成しておく必要があります。

.手順
. Cloud Insights メニューで、 * Manage > Annotation rules * の順にクリックします。
. 新しいアノテーションルールを追加するには、「 * + ルール * 」をクリックします。
+
[Add Rule] ダイアログが表示されます。

. 次の手順を実行します。
+
.. [* 名前 *] ボックスに、ルールを説明する一意の名前を入力します。
+
名前がアノテーションルールページに表示されます。

.. クエリ * をクリックし、アノテーション環境でアセットを識別するために Cloud Insights で使用するクエリを選択します。
.. [* Annotation* ] をクリックし、適用する注釈を選択します。
.. * 値 * をクリックし、アノテーションの値を選択します。
+
たとえば、 Birthday のアノテーションを選択した場合は、日付の値を指定します。

.. [ 保存（ Save ） ] をクリックします。
.. すべてのルールをすぐに実行する場合は、 * すべてのルールを実行 * をクリックします。それ以外の場合、ルールは定期的に実行されます。
+

NOTE: 大規模な Cloud Insights 環境では、アノテーションルールの実行が完了するまでに時間がかかるように見えることがあります。これは、インデクサが最初に実行され、ルールを実行する前に完了する必要があるためです。インデクサは、 Cloud Insights がデータ内の新規または更新されたオブジェクトやカウンタを検索またはフィルタリングできるようにする機能です。ルールエンジンは、インデクサが更新を完了するまで待機してから、ルールを適用します。







== アノテーションルールの変更

アノテーションルールについて、ルールの名前、そのアノテーション、アノテーションの値、ルールに関連付けられているクエリを変更することができます。

.手順
. Cloud Insights メニューで、 * Manage > Annotation rules * の順にクリックします。
+
アノテーションルールページに、既存のアノテーションルールのリストが表示されます。

. 変更するアノテーションルールを選択します。
+
アノテーションルールは、フィルタボックスに値を入力してフィルタすることも、ページ番号をクリックして各ページで参照することもできます。

. 変更するルールのメニューアイコンをクリックします。
. [ 編集（ Edit ） ] をクリックします。
+
Edit Rule ダイアログが表示されます。

. アノテーションルールの名前、アノテーション、値、またはクエリを変更します。




== ルールの順序を変更する

アノテーションルールは、ルールリストの一番上から一番下まで処理されます。ルールの処理順序を変更するには、次の手順を実行します。

.手順
. 移動するルールのメニューアイコンをクリックします。
. 目的の場所にルールが表示されるまで、必要に応じて [ 上へ移動 ] または [ 下へ移動 ] をクリックします。




== アノテーションルールを削除する

使用されなくなったアノテーションルールを削除できます。

.手順
. Cloud Insights メニューで、 * Manage > Annotation rules * の順にクリックします。
+
アノテーションルールページに、既存のアノテーションルールのリストが表示されます。

. 削除するアノテーションルールを選択します。
+
アノテーションルールは、フィルタボックスに値を入力してフィルタすることも、ページ番号をクリックして各ページで参照することもできます。

. 削除するルールのメニューアイコンをクリックします。
. [ 削除（ Delete ） ] をクリックします。
+
ルールを削除するかどうかを確認するメッセージが表示されます。

. [OK] をクリックします。

