---
sidebar: sidebar 
permalink: task_isolate_root_volume.html 
summary: 大量の I/O 密度を照会する際に、ルートボリュームを除外する。 
keywords: NetApp, root volume, high I/O, 
---
= I/O 密度レポートに内部データボリュームのみが記載されていることを確認する


[role="lead"]
ネットアップのルートボリュームには、ストレージシステムを管理するためのディレクトリと構成ファイルが格納されています。大量の I/O 密度を照会する際に、これらのルートボリュームを除外する。

環境を監視する際には、どの内部データボリュームが高い I/O 密度を生成しているかを特定することが重要です。データボリュームだけを正確に特定するには、ネットアップの内部ボリュームを、 I/O 密度の監視に使用するクエリから分離する必要があります。

このガイドでは、ネットアップのルートアグリゲートを簡単に特定し、それらを内部ボリュームのクエリの結果から分離する方法と、システムにネットアップの新しいルートアグリゲートが追加されるたびにそれらを除外するルールを作成する方法について説明します。I/O 密度レポートに内部データボリュームだけの情報を出力するには、 Insight の次の機能を使用します。

* Insight で監視しているネットアップのルートアグリゲートを特定するクエリを作成する。
* ネットアップのルートアグリゲートのそれぞれにアノテーションを割り当てる。
* 新しいネットアップのルートアグリゲートにアノテーションを適用するためのアノテーションルールが作成されます。


このガイドで説明する手順は、他のベンダーのストレージシステムにも適用できます。ストレージシステムを管理するためのディレクトリおよび構成ファイルが格納されたボリュームを特定し、同様の手順を使用してこれらのボリュームを除外する必要があります。



== 環境内でネットアップのルートアグリゲートを特定するクエリの作成

クエリは、ユーザが選択した条件に基づいて、細かいレベルまで検索する機能です。クエリを使用すると、ネットアップのルートアグリゲートが含まれている環境内の内部ボリュームを検索できます。

. 手順
. 環境内でネットアップのルートアグリゲートを特定するクエリを作成します。クリック * Queries > New Query > Select Resource Type * （？）
. [ ストレージプール ] をクリックします
. ルートアグリゲートの名前を入力します
+
この例では、名前に「 aggr0 」を使用します。アグリゲートの作成時には、次の要件に従って名前を指定する必要があります。先頭の文字にはアルファベットまたはアンダースコア（ _ ）を使用する必要があります。。アルファベット、数字、アンダースコアのみを使用できます。。250 文字以内で指定します。アグリゲートの名前は通常、 aggr0 、 aggr_0 などの形式にします。環境内のネットアップのルートアグリゲートをすべて特定するには、反復的なプロセスが必要となる場合があります。

. [ 保存（ Save ） ] をクリックし、新しい照会の名前を入力する。
+
前述のとおり、この作業は反復的なプロセスになる場合があり、ネットアップのすべてのルートアグリゲートを特定するために複数のクエリが必要になることがあります。





== クエリで返されるルートボリューム用のアノテーションを作成します

アノテーションはアセットに割り当てる特殊なメモで、アノテーションによってアセットをフィルタすることができます。作成したアノテーションは、環境内のネットアップのルートアグリゲートを特定し、それらのアグリゲートを特定のレポートに含めないようにするために使用します。

「 High I/O Density 」レポートから除外するルートアグリゲートをすべて特定しておく必要があります。

.手順
. Cloud Insights メニューで、 * Manage > Annotations * をクリックします
. [ 追加（ Add ） ] をクリックします。
+
.. アノテーションの名前として「 * RootAggr 」と入力します
.. アノテーションの概要として「 * Remove root aggregate from "High I/O Density" report * 」と入力します
.. アノテーションのタイプとして「 * Boolean * 」と入力します


. [ 保存（ Save ） ] をクリックします。




== I/O 密度に関するレポートから特定のアグリゲートを自動的に除外するためのアノテーションルールの作成

アノテーションを個々のアセットに手動で適用する代わりに、アノテーションルールを使用して複数のアセットに自動的にアノテーションを適用することができます。アノテーションルールは、ユーザが作成するクエリに基づいてシステム上で実行されるもので、新しいアセットを既存のアセットセットに追加します。これらのアセットセットをレポートから除外すると、新しいアセットも自動的に除外されます。

環境内で特定したネットアップのルートアグリゲートを識別するクエリを作成し、保存しておく必要があります。。手順Cloud Insights ツールバーで、 * 管理 > アノテーションルール * をクリックします。[ 追加（ Add ） ] をクリックします。

+ [Add Rule] ダイアログボックスが表示されます。名前ボックスに、ルール * "RootAggrExclude" * を記述する一意の名前を入力します。Query をクリックし、アノテーションルールを適用するために Insight で使用する Query を選択します。 * "Aggregate0" * 。Annotation をクリックして '*"Root agg exclude"*. を選択します「 * Value * 」をクリックし、「 * True * 」と入力します
