---
sidebar: sidebar 
permalink: task-verify-autosupport.html 
keywords: autosupport, set up autosupport, test autosupport, asup, test asup 
summary: AutoSupport は、システムの健常性をプロアクティブに監視し、ネットアップテクニカルサポートにメッセージを送信します。デフォルトでは、各ノードで AutoSupport が有効になっており、 HTTPS 転送プロトコルを使用してテクニカルサポートにメッセージを送信できます。AutoSupport がこれらのメッセージを送信できることを確認することをお勧めします。 
---
= AutoSupport のセットアップを確認します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
AutoSupport は、システムの健常性をプロアクティブに監視し、ネットアップテクニカルサポートにメッセージを送信します。デフォルトでは、各ノードで AutoSupport が有効になっており、 HTTPS 転送プロトコルを使用してテクニカルサポートにメッセージを送信できます。AutoSupport がこれらのメッセージを送信できることを確認することをお勧めします。

必要な設定手順は、 Cloud Volumes ONTAP がアウトバウンドインターネットに接続されていることを確認することだけです。詳細については、クラウドプロバイダのネットワーク要件を参照してください。



== AutoSupport の要件

Cloud Volumes ONTAP ノードには、NetApp AutoSupport へのアウトバウンドインターネットアクセスが必要です。ネットアップは、システムの健常性をプロアクティブに監視し、ネットアップテクニカルサポートにメッセージを送信します。

Cloud Volumes ONTAP が AutoSupport メッセージを送信できるように、ルーティングポリシーとファイアウォールポリシーで次のエンドポイントへの HTTP / HTTPS トラフィックを許可する必要があります。

* \https://support.netapp.com/aods/asupmessage
* \https://support.netapp.com/asupprod/post/1.0/postAsup


AutoSupport メッセージの送信にアウトバウンドのインターネット接続が使用できない場合、Cloud Volumes ONTAP システムは自動的にコネクタをプロキシサーバとして使用するように設定されます。唯一の要件は、コネクタのセキュリティグループがポート3128で_ inbound_connectionsを許可することです。コネクタを展開した後、このポートを開く必要があります。

Cloud Volumes ONTAP に厳密なアウトバウンドルールを定義した場合は、Cloud Volumes ONTAP セキュリティグループがポート3128で_OUTBOUND接続を許可する必要もあります。

アウトバウンドのインターネットアクセスが使用可能であることを確認したら、 AutoSupport をテストしてメッセージを送信できることを確認します。手順については、を参照してください https://docs.netapp.com/us-en/ontap/system-admin/setup-autosupport-task.html["ONTAP のドキュメント：「 AutoSupport のセットアップ"^]。



== AutoSupport 構成のトラブルシューティングを行います

アウトバウンド接続が使用できず、BlueXPがコネクタをプロキシサーバとして使用するようにCloud Volumes ONTAP システムを設定できない場合は、「<作業環境名> is unable to send AutoSupport messages」というBlueXPから通知が届きます。

ネットワークの問題が原因でこのメッセージが表示される可能性が高いです。

この問題に対処するには、次の手順を実行します。

.手順
. CLIからシステムを管理できるように、Cloud Volumes ONTAP システムにSSH接続します。
+
link:task-connecting-to-otc.html["Cloud Volumes ONTAP にSSH接続する方法について説明します"]。

. AutoSupport サブシステムの詳細なステータスを表示します。
+
`autosupport check show-details`

+
次のような応答が返されます。

+
[listing]
----
    Category: smtp
          Component: mail-server
             Status: failed
             Detail: SMTP connectivity check failed for destination:
                     mailhost. Error: Could not resolve host - 'mailhost'
            Corrective Action: Check the hostname of the SMTP server

    Category: http-https
        Component: http-put-destination
            Status: ok
            Detail: Successfully connected to:
                    <https://support.netapp.com/put/AsupPut/>.

          Component: http-post-destination
             Status: ok
             Detail: Successfully connected to:
                     https://support.netapp.com/asupprod/post/1.0/postAsup.

    Category: on-demand
          Component: ondemand-server
             Status: ok
             Detail: Successfully connected to:
                     https://support.netapp.com/aods/asupmessage.

    Category: configuration
            Component: configuration
                Status: ok
                Detail: No configuration issues found.
    5 entries were displayed.
----
+
http-httpsカテゴリのステータスが「ok」の場合は、AutoSupport が正しく設定されていて、メッセージを送信できることを意味します。

. ステータスがOKでない場合は、各Cloud Volumes ONTAP ノードのプロキシURLを確認します。
+
`autosupport show -fields proxy-url`

. プロキシURLパラメータが空の場合は、コネクタをプロキシとして使用するようにCloud Volumes ONTAP を設定します。
+
`autosupport modify -proxy-url \http://<connector private ip>:3128`

. AutoSupport のステータスを再度確認します。
+
`autosupport check show-details`

. このステータスがFAILEDの場合は、Cloud Volumes ONTAP とポート3128のコネクタの間に接続が確立されていることを確認します。
. 接続が確立されていることを確認したあともステータスIDに障害が発生している場合は、コネクタにSSHで接続します。
+
https://docs.netapp.com/us-en/bluexp-setup-admin/task-managing-connectors.html#connect-to-the-linux-vm["ConnectorのLinux VMへの接続の詳細については、を参照してください"^]

. に進みます `/opt/application/netapp/cloudmanager/docker_occm/data/`
. プロキシ構成ファイルを開く `squid.conf`
+
ファイルの基本構造は次のとおりです。

+
[listing]
----
        http_port 3128
        acl localnet src 172.31.0.0/16
        acl azure_aws_metadata dst 169.254.169.254

        http_access allow localnet
        http_access deny azure_aws_metadata
        http_access allow localhost
        http_access deny all
----
+
localnet srcの値は、Cloud Volumes ONTAP システムのCIDRです。

. Cloud Volumes ONTAP システムのCIDRブロックがファイルで指定された範囲にない場合は、値を更新するか、次のように新しいエントリを追加します。
+
`acl cvonet src <cidr>`

+
この新しいエントリを追加する場合は、許可エントリも追加することを忘れないでください。

+
`http_access allow cvonet`

+
次に例を示します。

+
[listing]
----
        http_port 3128
        acl localnet src 172.31.0.0/16
        acl cvonet src 172.33.0.0/16
        acl azure_aws_metadata dst 169.254.169.254

        http_access allow localnet
        http_access allow cvonet
        http_access deny azure_aws_metadata
        http_access allow localhost
        http_access deny all
----
. 設定ファイルを編集したら、sudoとしてプロキシコンテナを再起動します。
+
`docker restart squid`

. Cloud Volumes ONTAP のCLIに戻って、Cloud Volumes ONTAP からAutoSupport メッセージを送信できることを確認します。
+
`autosupport check show-details`


