---
sidebar: sidebar 
permalink: task_create_application.html 
summary: アノテーションルールを作成すると、定義した条件に基づいて複数のアセットにアノテーションを自動的に適用できます。 
keywords: application, create application, 
---
= アプリケーションの作成


[role="lead"]
環境で実行されている特定のアプリケーションに関連付けられているデータを追跡するには、 Cloud Insights でアプリケーションを定義します。

アプリケーションをビジネスエンティティに関連付ける場合は、アプリケーションを定義する前にビジネスエンティティを作成する必要があります。

Cloud Insights を使用すると、アプリケーションに関連付けられているアセットのデータを追跡して、使用状況やコストレポートなどの情報を確認できます。

。Cloud Insights メニューで、 * Manage > Applications * の順にクリックします。

+ ［ アプリケーションの追加 ］ ダイアログボックスが表示されます。

. アプリケーションの一意の名前を入力します。
. アプリケーションの優先度を選択します。
. [ 保存（ Save ） ] をクリックします。


アプリケーションを定義したら、アセットに割り当てることができます。



== アセットへのアプリケーションの割り当て

この手順では、例としてアプリケーションをホストに割り当てます。アプリケーションには、ホスト、仮想マシン、ボリューム、または内部ボリュームを割り当てることができます。

.手順
. アプリケーションに割り当てるアセットを選択します。
. [* クエリ ] 、 [ 新しいクエリ ] の順にクリックし、 [ ホスト ] を検索します。
. アプリケーションに関連付けるホストの左側にあるチェックボックスをオンにします。
. [ 一括操作 ]>[ アプリケーションの追加 *] をクリックします。
. アセットを割り当てるアプリケーションを選択します。


アプリケーションにホストを割り当てたら、残りのアセットをアプリケーションに割り当てることができます。アプリケーションのランディング・ページにアクセスするには、 * Manage > Application * をクリックして、作成したアプリケーションを選択します。
