---
sidebar: sidebar 
permalink: task_dc_ibm_ds4000.html 
keywords: data collector, IBM, DS4000 
summary: IBM TotalStorage DS4000 データコレクタ 
---
= IBM TotalStorage DS4000 データコレクタ
:allow-uri-read: 


[role="lead"]
このデータコレクタは 'IBM DS4000 ストレージ・システムからインベントリおよびパフォーマンス情報を取得します可能な構成は 2 種類（ファームウェア 6.x とファームウェア 7.x 以降）で、値はどちらも同じです。



== 用語集

Cloud Insightst は、 IBM DS4000 データコレクタから次のインベントリ情報を取得します。取得したアセットのタイプごとに、そのアセットに使用される最も一般的な用語が表示されます。このデータコレクタを表示またはトラブルシューティングするときは、次の用語に注意してください。

[cols="2*"]
|===
| ベンダー / モデルの用語 | Cloud Insights の用語 


| ディスク | ディスク 


| ボリュームグループ | ディスクグループ 


| ストレージアレイ | ストレージ 


| コントローラ | ストレージノード 


| ボリュームグループ | ストレージプール 


| ボリューム | ボリューム 
|===
注：これらは一般的な用語の対応のみを示したものであり、このデータコレクタのすべてのケースを表しているわけではありません。



== 要件

* DS5 または FAStT の各アレイの IP アドレス
* アレイの両方のコントローラの IP アドレスに ping を実行してアクセスを検証します
* ポート要件： 2463




== 設定

[cols="2*"]
|===
| フィールド | 説明 


| アレイ SANtricity コントローラの IP をカンマで区切ったリスト | アレイコントローラの IP アドレスまたは完全修飾ドメイン名 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 説明 


| インベントリポーリング間隔（分） | デフォルトは 30 分です 


| パフォーマンスポーリング間隔（最大 3600 秒） | デフォルト値は 300 秒です 
|===


== トラブルシューティング

この Data Collector の追加情報は、から入手できます link:concept_requesting_support.html["サポート"] ページまたはを参照してください link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector サポートマトリックス"]。
