---
sidebar: sidebar 
permalink: task_defining_annotations.html 
keywords: annotations, monitor, notes, tags 
summary: アノテーションを使用してデータを追跡する。 
---
= アノテーションの定義
:allow-uri-read: 


[role="lead"]
Cloud Insights をカスタマイズして会社の要件に合わせてデータを追跡するときは、アノテーションと呼ばれる特殊な注釈を定義してアセットに割り当てることができます。

アセットの終了日、データセンター、建物の場所、ストレージ階層、ボリュームのサービスレベルなどの情報をアノテーションに割り当てることができます。

環境の監視にアノテーションを使用すると、次の作業に役立ちます。

* すべてのアノテーションタイプの定義を作成または編集する。
* アセットページを表示し、各アセットを 1 つ以上のアノテーションに関連付ける。
+
たとえば、リースしているアセットのリース期限が 2 カ月以内の場合、終了日のアノテーションを適用すると、これにより、他のユーザがそのアセットを長期間使用できないようにすることができます。

* ルールを作成して、同じタイプの複数のアセットにアノテーションを自動的に適用する。
* アノテーションに基づいてアセットをフィルタする。




== デフォルトのアノテーションタイプ

Cloud Insights にはデフォルトのアノテーションタイプがいくつか用意されますこれらのアノテーションを使用して、データをフィルタまたはグループ化できます。

次のようなデフォルトのアノテーションタイプをアセットに関連付けることができます。

* アセットのライフサイクル：開始日、停止日、終了日など
* デバイスの場所の情報。データセンター、建物、フロアなど
* 品質（階層）、接続デバイス（スイッチレベル）、サービスレベルなどのアセットの分類
* ステータス（ホット（高利用率）など）


次の表に、 Cloud Insights が提供するアノテーションタイプを示します。

[cols="30,53, 16"]
|===


| アノテーションタイプ | 説明 | を入力します 


| エイリアス | リソースのフレンドリ名 | テキスト（ Text ） 


| コンピュートリソースグループ | Host and VM File Systems データコレクタで使用されるグループ割り当て | リスト 


| データセンター | 物理的な場所 | リスト 


| ホット | 使用頻度が高いデバイスが定期的に、または容量のしきい値に達しています | ブール値 


| 注 | リソースに関連付けられているコメント | テスト 


| サービスレベル | リソースに割り当てることができる一連のサポート対象サービスレベル。内部ボリューム、 qtree 、およびボリュームの番号付きのオプションのリストが用意されています。サービスレベルを編集して、各レベルのパフォーマンスポリシーを設定できます。 | リスト 


| 日没 | そのデバイスに新しい割り当てを実行できないしきい値。計画的な移行や保留中のネットワークの変更に役立ちます。 | 日付 


| スイッチレベル | スイッチのカテゴリを設定するための事前定義されたオプション。通常、これらの指定はデバイスのライフサイクルを通して維持されますが、編集することもできます。スイッチに対してのみ設定できます。 | リスト 


| 階層 | を使用すると、環境内のさまざまなサービスレベルを定義できます。階層では、必要な速度などのレベルを定義できます（例： Gold や Silver ）。この機能は、内部ボリューム、 qtree 、ストレージアレイ、ストレージプール、およびボリュームに対してのみ使用できます。 | リスト 


| 違反の重大度 | 違反（ホストポートの欠落や冗長性の欠如など）のランク（例： Major ）。重要度の高い順に階層化されています。 | リスト 
|===

NOTE: エイリアス、データセンター、ホット、サービスレベル、サンセット、 スイッチレベル、階層、および違反の重大度はシステムレベルのアノテーションであり、削除も名前変更もできません。変更できるのは、割り当てられている値のみです。



== カスタムアノテーションの作成

アノテーションを使用すると、ビジネスニーズに合わせて、ビジネス固有のカスタムデータをアセットに追加できます。Cloud Insights には一連のデフォルトアノテーションが用意されていますが、ほかにもさまざまな方法でデータを表示できます。カスタムアノテーションのデータは、ストレージのメーカー、ボリューム数、パフォーマンス統計など、すでに収集されたデバイスの補足データになります。アノテーションを使用して追加したデータは Cloud Insights で検出されません。

.手順
. Cloud Insights メニューで、 * Manage > Annotations * をクリックします
+
アノテーションページにアノテーションのリストが表示されます。

. 「 * + 追加」をクリックします。
. アノテーションの * Name * と * 概要 * を入力します。
+
これらのフィールドには、 255 文字まで入力できます。

. * タイプ * をクリックし、このアノテーションで使用できるデータのタイプを表す次のオプションのいずれかを選択します。


.アノテーションタイプ
ブール値:: 選択肢が yes と no のドロップダウンリストを作成しますたとえば、「 Direct Attached 」アノテーションはブーリアンです。
日付:: これにより、日付を保持するフィールドが作成されます。たとえば、アノテーションで日付を指定する場合は、このオプションを選択します。
リスト:: 次のいずれかを作成します。
+
--
* 固定のドロップダウンリスト
+
このアノテーションタイプをデバイスに割り当てるときにユーザがリストに値を追加することはできません。

* 可変のドロップダウンリスト
+
このリストを作成するときに [ オンザフライで新しい値を追加 ] オプションを選択すると、他のユーザーがこのアノテーションタイプをデバイスに割り当てるときに、リストに値を追加できます。



--
番号:: アノテーションを割り当てるユーザが数値を入力できるフィールドを作成します。たとえば、アノテーションタイプが「 floor 」の場合は、値タイプとして「 number 」を選択し、フロア番号を入力できます。
テキスト（ Text ）:: 自由形式のテキストを許可するフィールドを作成します。たとえば、アノテーションタイプとして「 Language 」と入力し、値のタイプとして「 Text 」を選択し、言語を値として入力できます。



NOTE: タイプを設定して変更を保存したあとで、アノテーションのタイプを変更することはできません。タイプを変更する必要がある場合は、アノテーションを削除して新規に作成する必要があります。

. アノテーションタイプとして List を選択した場合は、次の手順を実行します。
+
.. アセットページでアノテーションの値を追加して柔軟なリストを作成できるようにするには、「 * オンザフライで新しい値を追加」を選択します。
+
たとえば、アセットページで、 Detroit 、 Tampa 、および Boston の値が設定された City アノテーションをアセットに割り当てているとします。「 * オンザフライで新しい値を追加」オプションを選択した場合は、「アノテーション」ページに移動して値を追加する代わりに、アセットページでサンフランシスコやシカゴなどの都市に直接値を追加できます。このオプションを選択しないと、アノテーションの適用時に新しいアノテーション値を追加できません。これにより固定リストが作成されます。

.. 値（ Value ）と * 値（ * Value ） * および * 概要 * （ * 概要 * ）フィールドに値（ ）を入力する。
.. 値を追加するには、 [*+Add+*] をクリックします。
.. 「ゴミ箱」アイコンをクリックして値を削除します。


. [ 保存（ Save ） ] をクリックします。
+
アノテーションがアノテーションページのリストに表示されます。



UI では、アノテーションがすぐに使用可能になります。
