---
sidebar: sidebar 
permalink: task_device_resolution_rules.html 
keywords: Automatic, AR, AHR, Host, automatic device resolution 
summary: デバイス解決は、環境内のパフォーマンスとインベントリを正確に追跡するのに役立ちます。 
---
= デバイス解決ルール
:allow-uri-read: 


[role="lead"]
Cloud Insights で現在は自動的に識別されないホスト、ストレージ、およびテープを識別するためのデバイス解決ルールを作成します。作成したルールにより、環境内の既存のデバイスが識別されるほか、環境に追加された同様のデバイスも識別されます。



== デバイス解決ルールの作成

ルールを作成するときは、最初に、ルールの実行対象となる情報のソース、情報の抽出に使用する方法、およびルールの結果に DNS ルックアップを適用するかどうかを特定します。

[cols="2*"]
|===


| デバイスの識別に使用するソース | * ホストの SRM エイリアス * ホスト名またはテープ名が組み込まれたホスト・エイリアス * ホスト名またはテープ名が含まれるスイッチ・エイリアス * ホスト名が組み込まれたゾーン名 


| ソースからデバイス名を抽出する方法 | * そのまま（ SRM から名前を抽出） * デリミタ * 正規表現 


| DNS ルックアップ | ホスト名の検証に DNS を使用するかどうかを指定します 
|===
ルールは、 ［ 自動解決ルール ］ タブで作成します。以下に、ルールの作成プロセスについて説明します。

.手順
. [*Manage] > [Device Resolution*] をクリックします
. 自動解決ルール * タブで、 * + ホストルール * または * + テープルール * をクリックします。
+
[* 解決ルール * （ Resolution Rule ） ] 画面が表示されます。

+

NOTE: 正規表現の作成に関するヘルプと例については、 _View matching_criteria リンクをクリックしてください。

. [* タイプ ] リストで、識別するデバイスを選択します。
+
ホストまたはテープを選択できます。

. [ * ソース * ] リストで、ホストの識別に使用するソースを選択します。
+
選択したソースに応じて、 Cloud Insights は次の応答を表示します。

+
.. * ゾーン * には、 Cloud Insights で識別する必要があるゾーンおよび WWN がリストされています。
.. *SRM * には、 Cloud Insights で識別する必要がある未識別のエイリアスがリストされています
.. * ストレージ・エイリアス * には、 Cloud Insights で識別する必要があるストレージ・エイリアスおよび WWN がリストされています
.. * Switch alias * には、 Cloud Insights で識別する必要があるスイッチエイリアスを示します


. メソッド * リストで、ホストの識別に使用する方法を選択します。
+
|===


| ソース | メソッド 


| SRM の場合 | そのままで、デリミタ、正規表現を使用します 


| ストレージエイリアス | デリミタ、正規表現 


| スイッチエイリアス | デリミタ、正規表現 


| ゾーン | デリミタ、正規表現 
|===
+
** Delimiters を使用するルールの場合は、デリミタとホスト名の最小文字数を指定する必要があります。ホスト名の最小文字数は、 Cloud Insights がホストの識別に使用する文字数です。Cloud Insights は、この文字数以上のホスト名に対してのみ DNS ルックアップを実行します。
+
delimiters を使用するルールの場合、入力文字列は区切り文字でトークン化され、ホスト名候補のリストは、隣接するトークンを複数組み合わせて作成されます。リストは、最大から最小にソートされます。たとえば '_vipsnq03_hba3_emc3_12ep0_ の入力 sring の場合 ' リストは次のようになります

+
*** vipsnq03_hba3_emc3_12ep0
*** vipsnq03_hba3_emc3
*** hba3 emc3_12ep0
*** vipsnq03_hba3.
*** emc3_12ep0
*** hba3_emc3
*** vipsnq03
*** 12ep0
*** emcs3
*** hba3.


** 正規表現を使用するルールでは、正規表現、形式、および大文字と小文字の区別を選択する必要があります。


. すべてのルールを実行するには、 * Run AR * をクリックします。または、ボタンの下矢印をクリックして、作成したルール（および前回の AR のフル実行後に作成された他のルール）を実行します。
+
ルールの実行結果は、 * FC identify * タブに表示されます。





== 自動デバイス解決の更新を開始しています

デバイス解決の更新では、前回の完全な自動デバイス解決の実行後に手動で行った変更がコミットされます。更新を実行すると、デバイス解決設定に対する新しい手動のエントリのみをコミットして実行できます。完全なデバイス解決は実行されません。

.手順
. Cloud Insights Web UI にログインします。
. [*Manage] > [Device Resolution*] をクリックします
. [ * デバイス解決 * ] 画面で、 [* AR の実行 ] ボタンの下矢印をクリックします。
. アップデートを開始するには、 * アップデート * をクリックします。




== ルールに基づく手動識別

この機能は、不明なホスト、ストレージ、テープデバイスを解決するために特定のルールまたはルールのリストを（ 1 回だけ順序変更の有無に関係なく）実行する場合に使用します。

.作業を開始する前に
識別されていないデバイスが多数あり、他のデバイスを正しく識別した複数のルールがある場合。


NOTE: ソースにホスト名またはデバイス名の一部だけが含まれている場合は、正規表現のルールを使用して欠落しているテキストを追加するように形式を変更します。

.手順
. Cloud Insights Web UI にログインします。
. [*Manage] > [Device Resolution*] をクリックします
. Fibre Channel identify * タブをクリックします。
+
デバイスとその解決ステータスが表示されます。

. 識別されていない複数のデバイスを選択
. [ * Bulk Actions * ] をクリックし、 [ * ホスト解決の設定 * ] または [ * テープ解決の設定 * ] を選択します。
+
識別画面が表示され、デバイスを正しく識別したすべてのルールのリストが表示されます。

. ルールの順序を、ニーズに合った順序に変更します。
+
ルールの順序は識別画面で変更されますが、グローバルには変更されません。

. ニーズに合った方法を選択します。


Cloud Insights は、上から順に表示された方法に従ってホスト解決プロセスを実行します。

適用されるルールが検出されると、ルールの名前がルールの列に表示され、手動で識別されます。

関連：link:task_device_resolution_fibre_channel.html["ファイバチャネルのデバイス解決"]
link:task_device_resolution_ip.html["IP デバイス解決"]
link:task_device_resolution_preferences.html["デバイス解決のプリファレンスの設定"]
