---
sidebar: sidebar 
permalink: task_dc_emc_ecs.html 
keywords: data collector, ecs, EMC 
summary: ECS データコレクタの設定。 
---
= EMC ECS データコレクタの設定
:allow-uri-read: 


[role="lead"]
このデータコレクタは、 EMC ECS ストレージシステムからインベントリデータとパフォーマンスデータを取得します。データコレクタを設定するには、 ECS サーバの IP アドレスと管理レベルのドメインアカウントが必要です。



== 用語集

Cloud Insights は、 ECS データコレクタから次のインベントリ情報を取得します。取得したアセットのタイプごとに、そのアセットに使用される最も一般的な用語が表示されます。このデータコレクタを表示またはトラブルシューティングするときは、次の用語に注意してください。

[cols="2*"]
|===
| ベンダー / モデルの用語 | Cloud Insights の用語 


| クラスタ | ストレージ 


| テナント | ストレージプール 


| バケット | 内部ボリューム 


| ディスク | ディスク 
|===
注：これらは一般的な用語の対応のみを示したものであり、このデータコレクタのすべてのケースを表しているわけではありません。



== 要件

* ECS 管理コンソールの IP アドレス
* ECS システムの管理者レベルドメインアカウント
* ポート 443 （ HTTPS ）：ECS システムで TCP ポート 443 へのアウトバウンド接続が必要です。
* パフォーマンスを確保するには、 ssh/scp アクセス用の読み取り専用のユーザ名とパスワードを使用します。
* パフォーマンスを確保するには、ポート 22 が必要です。




== 設定

[cols="2*"]
|===
| フィールド | 説明 


| ECS ホスト | ECS システムの IP アドレスまたは完全修飾ドメイン名 


| ECS ホストポート | ECS ホストとの通信に使用されるポート 


| ECS ベンダー ID | ECS のベンダー ID 


| パスワード | ECS のパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 説明 


| インベントリポーリング間隔（分） | デフォルトは 360 分です。 
|===


== トラブルシューティング

追加情報はから入手できます link:concept_requesting_support.html["サポート"] ページまたはを参照してください link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector サポートマトリックス"]。
