---
sidebar: sidebar 
permalink: task_dc_na_cdot.html 
keywords: data collector, ontap, ontap, CDOT 
summary: ONTAP データコレクタ 
---
= NetApp ONTAP データ管理ソフトウェアのデータコレクタ


[role="lead"]
このデータコレクタは、 ONTAP アカウントからの読み取り専用の API 呼び出しを使用して、 ONTAP を実行しているストレージシステムからインベントリとパフォーマンスのデータを取得します。このデータコレクタは、サポートを高速化するために、クラスタアプリケーションレジストリにレコードを作成します。



== 用語集

Cloud Insights は、 ONTAP データコレクタからインベントリデータとパフォーマンスデータを取得します。取得したアセットのタイプごとに、そのアセットに使用される最も一般的な用語が表示されます。このデータコレクタを表示またはトラブルシューティングするときは、次の用語に注意してください。

[cols="2*"]
|===
| ベンダー / モデルの用語 | Cloud Insights の用語 


| ディスク | ディスク 


| RAID グループ | ディスクグループ 


| クラスタ | ストレージ 


| ノード | ストレージノード 


| アグリゲート | ストレージプール 


| LUN | ボリューム 


| ボリューム | 内部ボリューム 
|===


== ONTAP データ管理の用語

ONTAP データ管理ストレージのアセットランディングページにあるオブジェクトや参考資料に関連する用語を次に示します。これらの用語の多くは、他のデータコレクタにも適用されます。



=== ストレージ

* model –このクラスタ内で一意のディスクリートノードのモデル名をカンマで区切って指定します。クラスタ内のすべてのノードのモデルタイプが同じ場合、表示されるモデル名は 1 つだけです。
* Vendor –新しいデータソースを設定する場合に表示されるベンダー名と同じです。
* Serial Number –アレイのシリアル番号。ONTAP データ管理などのクラスタアーキテクチャストレージシステムでは、このシリアル番号は個々の「ストレージノード」のシリアル番号よりも有用性が低い場合があります。
* IP –一般に、データソースで設定されている IP またはホスト名です。
* マイクロコードバージョン–ファームウェア。
* raw 容量–システム内のすべての物理ディスクの合計 2 進数で、役割に関係なく加算されます。
* レイテンシ–読み取りと書き込みの両方について、ワークロードが直面しているホストの状況が表示されます。Cloud Insights がこの値を直接調達するのが理想的ですが、これは多くの場合ではありません。Cloud Insights は、このアップを提供するアレイの代わりに、通常、個々の内部ボリュームの統計情報から導出される IOPS 加重計算を実行します。
* スループット–内部ボリュームから集約されたもの。管理–デバイスの管理インターフェイスのハイパーリンクが含まれている可能性があります。Cloud Insights データソースによって、インベントリレポートの一部としてプログラムによって作成されます。




=== ストレージプール

* storage –このプールのストレージアレイの場所。必須。
* Type –可能性のリストから説明的な値を入力します。最も一般的な構成は、「集約」または「 RAID グループ」です。
* ノード：プールが特定のストレージノードに属するようなストレージアレイのアーキテクチャの場合、その名前は、そのストレージアレイのランディングページへのハイパーリンクとして表示されます
* Flash Pool を使用–値はあり / いいえ–この SATA / SAS ベースのプールでは、 SSD をキャッシュ高速化に使用していますか？
* 冗長性– RAID レベルまたは保護方式。raid_dp はデュアルパリティ、 raid_dp はトリプルパリティです。
* 容量–使用済みの論理容量、使用可能な容量、および合計論理容量の値と、これらの要素で使用されている割合の値が表示されます。
* オーバーコミット容量–効率化テクノロジを使用して、ストレージプールの論理容量よりも大きいボリュームまたは内部ボリュームの容量の合計を割り当てている場合、この割合は 0% よりも大きくなります。
* スナップショット–スナップショット専用のセグメント領域にストレージプールアーキテクチャが容量の一部を割り当てている場合に使用されるスナップショット容量と合計容量。MetroCluster 構成の ONTAP はこのような構成を示しますが、それ以外の ONTAP 構成はそうではありません。
* 利用率–このストレージプールに容量を追加しているディスクのビジー率の最大値を示した割合。ディスク利用率にアレイのパフォーマンスとの間に大きな相関関係があるとは限りません。ホストベースのワークロードがない場合は、ディスクのリビルドや重複排除処理などが原因で、利用率が高くなる可能性があります。また、多くのアレイのレプリケーション実装では、内部ボリュームやボリュームのワークロードとしては表示されずにディスク使用率が向上する場合があります。
* IOPS –このストレージプールに容量の要因となっているすべてのディスクの合計 IOPS 。Throughput –このストレージプールの容量の要因となっているすべてのディスクの合計スループット。




=== ストレージノード

* Storage –このノードが属するストレージアレイ。必須。
* HA パートナー–通常、一方のノードだけにフェイルオーバーするプラットフォームでは、この画面が表示されます。
* State –ノードの健常性。アレイが正常な状態でデータソースでインベントリを作成できる場合にのみ使用できます。
* model - ノードのモデル名。
* Version ：デバイスのバージョン名。
* シリアル番号–ノードのシリアル番号。
* メモリ–ベース 2 のメモリがあればそれ。
* 使用率– ONTAP では、これは独自のアルゴリズムのコントローラ応力インデックスです。パフォーマンスポーリングが行われるたびに、 WAFL ディスクの競合率または平均 CPU 利用率の値が 0 ～ 100% の範囲で報告されます。継続的に測定される値が 50% を超えている場合は、サイジングが不十分であることを示します。コントローラやノードのサイズが十分でないか、書き込みワークロードを吸収するのに十分な回転式ディスクが足りない可能性があります。
* IOPS –ノードオブジェクトの ONTAP ZAPI コールから直接取得されます。
* レイテンシ–ノードオブジェクトの ONTAP ZAPI コールから直接取得されます。
* スループット–ノードオブジェクトの ONTAP ZAPI コールから直接取得されます。
* プロセッサ– CPU 数。




== 要件

このデータコレクタを設定して使用するための要件は次のとおりです。

* 読み取り専用の API 呼び出し用に設定された管理者アカウントへのアクセス権が必要です。
* アカウントの詳細には、ユーザ名とパスワードが含まれます。
* ポートの要件： 80 または 443
* アカウントの権限：
+
** デフォルトの SVM の ONTAPI アプリケーションに対する読み取り専用のロール名
** オプションの書き込み権限が追加で必要になる場合があります。以下の「アクセス権に関する注意」を参照してください。


* ONTAP ライセンスの要件：
+
** ファイバチャネル検出に必要な FCP ライセンスおよびマッピング / マスクされたボリューム






== 設定

[cols="2*"]
|===
| フィールド | 説明 


| ネットアップ管理 IP | ネットアップクラスタの IP アドレスまたは完全修飾ドメイン名 


| ユーザ名 | ネットアップクラスタのユーザ名 


| パスワード | ネットアップクラスタのパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 説明 


| 接続タイプ | HTTP （デフォルトポート 80 ）または HTTPS （デフォルトポート 443 ）を選択します。デフォルトは HTTPS です 


| 通信ポートをオーバーライドします | デフォルト以外のポートを使用する場合は、別のポートを指定します 


| インベントリポーリング間隔（分） | デフォルトは 60 分です。 


| TLS では HTTPS を使用します | HTTPS を使用する場合にのみ TLS をプロトコルとして許可します 


| ネットグループを自動的に検索する | エクスポートポリシールールのネットグループの自動検索を有効にします 


| ネットグループの拡張 | ネットグループ拡張戦略：_FILE _ または _SHELL _ を選択します。デフォルトは _shell_ です。 


| HTTP 読み取りタイムアウト秒数 | デフォルトは 30 です 


| 応答を UTF-8 として強制実行します | データコレクタコードに、 CLI からの応答を UTF-8 であると解釈させます 


| パフォーマンスポーリング間隔（秒） | デフォルト値は 900 秒です。 


| 高度なカウンタデータ収集 | ONTAP の統合を有効にします。ONTAP 詳細カウンタデータをポーリングに含める場合に選択します。リストから目的のカウンタを選択します。 
|===


== アクセス権に関する注意事項

多くの Cloud Insights の ONTAP ダッシュボードは高度な ONTAP カウンタに依存するため、データコレクタの詳細設定セクションで * 高度なカウンタデータ収集 * を有効にする必要があります。

また、 ONTAP API への書き込み権限が有効になっていることも確認する必要があります。通常は、必要な権限を持つアカウントがクラスタレベルで必要になります。

クラスタレベルで Cloud Insights のローカルアカウントを作成するには、クラスタ管理者のユーザ名とパスワードを使用して ONTAP にログインし、 ONTAP サーバで次のコマンドを実行します。

. 次のコマンドを使用して、読み取り専用ロールを作成します。
+
....
security login role create -role ci_readonly -cmddirname DEFAULT -access readonly
security login role create -role ci_readonly -cmddirname security -access readonly
security login role create -role ci_readonly -access all -cmddirname “cluster application-record create”
....
. 次のコマンドを使用して、読み取り専用ユーザを作成します。create コマンドを実行すると、このユーザのパスワードを入力するように求められます。
+
 security login create -username ci_user -application ontapi -authentication-method password -role ci_readonly


AD / LDAP アカウントを使用する場合は、コマンドをに設定します

 security login create -user-or-group-name DOMAIN\aduser/adgroup -application ontapi -authentication-method domain -role ci_readonly
作成されるロールとユーザログインは次のようになります。

....
Role Command/ Access
Vserver Name Directory Query Level
---------- ------------- --------- ------------------ --------
cluster1 ci_readonly DEFAULT read only
cluster1 ci_readonly security readonly
....
....
cluster1::security login> show
Vserver: cluster1
Authentication Acct
UserName    Application   Method      Role Name      Locked
---------   -------      ----------- -------------- --------
ci_user     ontapi      password    ci_readonly   no
....


== トラブルシューティング

このデータコレクタで問題が発生した場合の対処方法を次に示します。



==== 在庫

[cols="2*"]
|===
| 問題 | 次の操作を実行します 


| 401 HTTP 応答または 13003 ZAPI エラーコードを受信し、 ZAPI から「 Insufficient privileges 」または「 Not authorized for this command 」が返される | ユーザ名とパスワード、およびユーザの権限と権限を確認してください。 


| クラスタバージョンが 8.1 より前である必要があります | クラスタでサポートされる最小バージョンは 8.1 です。サポートされる最小バージョンにアップグレードしてください。 


| ZAPI から「 cluster role is not cluster_mgmt LIF 」が返される | AU はクラスタ管理 IP と通信する必要があります。IP を確認し、必要に応じて別の IP に変更してください 


| エラー：「 7-Mode のストレージシステムはサポートされていません」 | この問題は、このデータコレクタを使用して 7-Mode ファイラーを検出した場合に発生することがあります。IP を変更して、代わりに cdot クラスタを指すようにします。 


| ZAPI コマンドの再試行後に失敗する | AU でクラスタとの通信に問題があります。ネットワーク、ポート番号、および IP アドレスを確認してください。また、 AU マシンのコマンドラインからもコマンドを実行しようとします。 


| AU が HTTP 経由で ZAPI に接続できませんでした | ZAPI ポートでプレーンテキストが受け入れるかどうかを確認します。AU が SSL ソケットにプレーンテキストを送信しようとすると、通信に失敗します。 


| SSLException で通信が失敗します | AU が Filer 上のプレーンテキストポートに SSL を送信しようとしています。ZAPI ポートで SSL を受け入れるか、別のポートを使用するかを確認します。 


| その他の接続エラー： ZAPI 応答にはエラーコード 13001 、「 database is not open 」 ZAPI エラーコード 60 があり、応答に「 API did not finished on time 」という応答が含まれています。 ZAPI エラーコード 14007 では「 initialize_session() returned NULL environment 」が返され、応答に「 Node is not healthy 」が含まれます。 | ネットワーク、ポート番号、および IP アドレスを確認してください。また、 AU マシンのコマンドラインからもコマンドを実行しようとします。 
|===


==== パフォーマンス

[cols="2*"]
|===
| 問題 | 次の操作を実行します 


| 「 ZAPI からパフォーマンスを収集できませんでした」というエラーが表示される | これは通常、 perf stat が実行されていないことが原因です。各ノードで次のコマンドを実行します。 >_system node systemshell -node * command "spmcctl -h cmd – stop; spmcctl -h cmd – exec" _ 
|===
追加情報はから入手できます link:concept_requesting_support.html["サポート"] ページまたはを参照してください link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector サポートマトリックス"]。
