---
sidebar: sidebar 
permalink: task-planning-your-config-gcp.html 
keywords: license, disk, ebs, storage, size, write speed, volume usage, capacity, limit, configurations, virtual machine, vm, regions, supported disks, disk types, use profile, thin provisioning, deduplication, compression, shared instance, dedicated instance, write speed, high write speed, normal write speed, network information, worksheet, limit, limits, storage limits, volume limit, aggregate limit, maximum volume size, maximum aggregate size, supported machine types, supported virtual machines, supported vms, supported instances 
summary: Cloud Volumes ONTAP を導入する場合は、ワークロード要件に一致する事前設定済みのシステムを選択するか、独自の構成を作成できます。独自の設定を選択する場合は、使用可能なオプションを理解しておく必要があります。 
---
= Google CloudでCloud Volumes ONTAP 構成を計画する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Google Cloud に Cloud Volumes ONTAP を導入する場合は、ワークロードの要件に合わせて事前設定されたシステムを選択するか、または独自の設定を作成できます。独自の設定を選択する場合は、使用可能なオプションを理解しておく必要があります。



== Cloud Volumes ONTAP ライセンスを選択します

Cloud Volumes ONTAP には、いくつかのライセンスオプションがあります。それぞれのオプションで、ニーズに合った消費モデルを選択できます。

* link:concept-licensing.html["Cloud Volumes ONTAP のライセンスオプションについて説明します"]
* link:task-set-up-licensing-google.html["ライセンスの設定方法について説明します"]




== サポートされているリージョンを選択します

Cloud Volumes ONTAP は、ほとんどの Google Cloud リージョンでサポートされています。 https://cloud.netapp.com/cloud-volumes-global-regions["サポートされているリージョンの完全なリストを表示します"^]。



== サポートされているマシンタイプを選択してください

Cloud Volumes ONTAP では、選択したライセンスタイプに応じて、複数のマシンタイプがサポートされます。

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["GCP の Cloud Volumes ONTAP でサポートされている構成"^]



== ストレージの制限を確認

Cloud Volumes ONTAP システムの未フォーマット時の容量制限は、ライセンスに関連付けられています。追加の制限は、アグリゲートとボリュームのサイズに影響します。設定を計画する際には、これらの制限に注意する必要があります。

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-limits-gcp.html["GCP の Cloud Volumes ONTAP でのストレージの制限"^]



== GCPでシステムをサイジングする

Cloud Volumes ONTAP システムのサイジングを行うことで、パフォーマンスと容量の要件を満たすのに役立ちます。マシンタイプ、ディスクタイプ、およびディスクサイズを選択する際には、次の点に注意してください。

マシンのタイプ:: でサポートされているマシンタイプを確認します http://docs.netapp.com/cloud-volumes-ontap/us-en/index.html["Cloud Volumes ONTAP リリースノート"^] 次に、サポートされている各マシンタイプについて Google の詳細を確認します。ワークロードの要件を、マシンタイプの vCPU とメモリの数と一致させます。各 CPU コアは、ネットワークパフォーマンスを向上させることに注意してください。
+
--
詳細については、以下を参照してください。

* https://cloud.google.com/compute/docs/machine-types#n1_machine_types["Google Cloud ドキュメント： N1 標準マシンタイプ"^]
* https://cloud.google.com/docs/compare/data-centers/networking#performance["Google Cloud のドキュメント：「 Performance"^]


--
GCPディスクタイプ:: Cloud Volumes ONTAP 用のボリュームを作成する際には、 Cloud Volumes ONTAP がディスクに使用する基盤となるクラウドストレージを選択する必要があります。ディスクタイプは次のいずれかです。
+
--
* _ゾーン SSD 永続ディスク _ ： SSD 永続ディスクは、ランダム IOPS が高いワークロードに最適です。
* _ゾーン バランシング永続ディスク _ ：これらの SSD は、 GB あたりの IOPS を下げて、パフォーマンスとコストのバランスを取ります。
* _Zonal 標準パーシステントディスク _ ：標準パーシステントディスクは経済的で、シーケンシャルな読み取り / 書き込み処理に対応できます。
+
詳細については、を参照してください https://cloud.google.com/compute/docs/disks/#pdspecs["Google Cloud のドキュメント：「ゾーン永続ディスク（標準および SSD ）」"^]。



--
GCPディスクサイズ:: Cloud Volumes ONTAP システムを導入する際には、初期ディスクサイズを選択する必要があります。システムの容量をBlueXPで管理できるようになりますが、自分でアグリゲートを作成する場合は、次の点に注意してください。
+
--
* アグリゲート内のディスクはすべて同じサイズである必要があります。
* パフォーマンスを考慮しながら、必要なスペースを判断します。
* パーシステントディスクのパフォーマンスは、システムで使用可能なディスクサイズと vCPU の数に応じて自動的に拡張されます。
+
詳細については、以下を参照してください。

+
** https://cloud.google.com/compute/docs/disks/#pdspecs["Google Cloud のドキュメント：「ゾーン永続ディスク（標準および SSD ）」"^]
** https://cloud.google.com/compute/docs/disks/performance["Google Cloud のドキュメント：「 Optimizing Persistent Disk and Local SSD Performance"^]




--




== デフォルトのシステムディスクを表示します

ユーザデータ用のストレージに加えて、BlueXPはCloud Volumes ONTAP システムデータ（ブートデータ、ルートデータ、コアデータ、NVRAM）用のクラウドストレージも購入します。計画を立てる場合は、 Cloud Volumes ONTAP を導入する前にこれらの詳細を確認すると役立つ場合があります。

* link:reference-default-configs.html#google-cloud-single-node["Cloud Volumes ONTAP システムデータ用のデフォルトディスクを Google Cloud で表示します"]。
* https://cloud.google.com/compute/quotas["Google Cloud のドキュメント：リソースクォータ"^]
+
Google Cloud Compute Engine では、リソース使用量にクォータが適用されるため、 Cloud Volumes ONTAP を導入する前に制限に達していないことを確認する必要があります。




TIP: コネクタにはシステムディスクも必要です。 https://docs.netapp.com/us-en/bluexp-setup-admin/reference-connector-default-config.html["コネクタのデフォルト設定に関する詳細を表示します"^]。



== ネットワーク情報を収集

GCP で Cloud Volumes ONTAP を導入する場合は、仮想ネットワークの詳細を指定する必要があります。ワークシートを使用して、管理者から情報を収集できます。

* シングルノードシステム * のネットワーク情報

[cols="30,70"]
|===
| GCP情報 | あなたの価値 


| 地域 |  


| ゾーン |  


| vPC ネットワーク |  


| サブネット |  


| ファイアウォールポリシー（独自のポリシーを使用している場合） |  
|===
* 複数ゾーン内の HA ペアのネットワーク情報 *

[cols="30,70"]
|===
| GCP情報 | あなたの価値 


| 地域 |  


| ノード 1 のゾーン |  


| ノード2のゾーン |  


| メディエーターのゾーン |  


| vPC-0 およびサブネット |  


| vPC-1 とサブネット |  


| vPC-2 およびサブネット |  


| vPC-3 とサブネット |  


| ファイアウォールポリシー（独自のポリシーを使用している場合） |  
|===
* 単一ゾーン内の HA ペアのネットワーク情報 *

[cols="30,70"]
|===
| GCP情報 | あなたの価値 


| 地域 |  


| ゾーン |  


| vPC-0 およびサブネット |  


| vPC-1 とサブネット |  


| vPC-2 およびサブネット |  


| vPC-3 とサブネット |  


| ファイアウォールポリシー（独自のポリシーを使用している場合） |  
|===


== 書き込み速度を選択します

BlueXPを使用すると、Google Cloudのハイアベイラビリティ（HA）ペアを除き、Cloud Volumes ONTAP の書き込み速度設定を選択できます。書き込み速度を選択する前に、高速書き込みを使用する場合の標準設定と高設定の違い、およびリスクと推奨事項を理解しておく必要があります。 link:concept-write-speed.html["書き込み速度の詳細については、こちらをご覧ください。"]。



== ボリュームの使用プロファイルを選択してください

ONTAP には、必要なストレージの合計容量を削減できるストレージ効率化機能がいくつか搭載されています。BlueXPでボリュームを作成するときに、これらの機能を有効にするプロファイル、または無効にするプロファイルを選択できます。これらの機能の詳細については、使用するプロファイルを決定する際に役立ちます。

NetApp Storage Efficiency 機能には、次のようなメリットがあります。

シンプロビジョニング:: 物理ストレージプールよりも多くの論理ストレージをホストまたはユーザに提供します。ストレージスペースは、事前にストレージスペースを割り当てる代わりに、データの書き込み時に各ボリュームに動的に割り当てられます。
重複排除:: 同一のデータブロックを検索し、単一の共有ブロックへの参照に置き換えることで、効率を向上します。この手法では、同じボリュームに存在するデータの冗長ブロックを排除することで、ストレージ容量の要件を軽減します。
圧縮:: プライマリ、セカンダリ、アーカイブストレージ上のボリューム内のデータを圧縮することで、データの格納に必要な物理容量を削減します。

