---
sidebar: sidebar 
permalink: task-azure-high-availability-mode.html 
keywords: high availability mode, EnableHighAvailabilityMode, action required, nfsv4 
summary: Microsoft Azureの高可用性モードを有効にして、計画外のフェイルオーバー時間を短縮し、NFSv4でCloud Volumes ONTAP がサポートされるようにする必要があります。 
---
= Azureでハイアベイラビリティモードを有効にします
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Microsoft Azureの高可用性モードを有効にして、計画外のフェイルオーバー時間を短縮し、NFSv4でCloud Volumes ONTAP がサポートされるようにする必要があります。

Cloud Volumes ONTAP 9.10.1リリースから、Microsoft Azureで実行されるCloud Volumes ONTAP HAペアの計画外フェイルオーバー時間が短縮され、NFSv4がサポートされるようになりました。これらの機能拡張をCloud Volumes ONTAP で使用できるようにするには、Azureサブスクリプションでハイアベイラビリティ機能を有効にする必要があります。

Azureサブスクリプションでこの機能を有効にする必要がある場合、「Action Required」メッセージにこれらの詳細が表示されます。

次の点に注意してください。

* Cloud Volumes ONTAP HA ペアの高可用性に問題はありません。この Azure 機能は、 ONTAP と連携して動作し、計画外のフェイルオーバーによって発生する NFS プロトコルのアプリケーション停止時間を短縮します。
* この機能を有効にしても、 Cloud Volumes ONTAP HA ペアの処理は中断されません。
* Azure サブスクリプションでこの機能を有効にしても、他の VM で原因の問題は発生しません。


「Owner」権限があるAzureユーザは、Azure CLIからこの機能を有効にできます。

.手順
. https://docs.microsoft.com/en-us/azure/cloud-shell/quickstart["Azure PortalからAzure Cloud Shellにアクセスします"^]
. ハイアベイラビリティモード機能を登録します。
+
[source, azurecli]
----
az account set -s AZURE_SUBSCRIPTION_NAME_OR_ID
az feature register --name EnableHighAvailabilityMode --namespace Microsoft.Network
az provider register -n Microsoft.Network
----
. 必要に応じて、機能が登録されたことを確認します。
+
[source, azurecli]
----
az feature show --name EnableHighAvailabilityMode --namespace Microsoft.Network
----
+
Azure CLIから次のような結果が返されることを確認します。

+
[listing]
----
{
  "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/providers/Microsoft.Features/providers/Microsoft.Network/features/EnableHighAvailabilityMode",
  "name": "Microsoft.Network/EnableHighAvailabilityMode",
  "properties": {
    "state": "Registered"
  },
  "type": "Microsoft.Features/providers/features"
}
----

