---
sidebar: sidebar 
permalink: task_create_annotation.html 
keywords: annotations, annotation rules, manual annotations, 
summary: アノテーションの作成方法 
---
= アノテーションの使用
:allow-uri-read: 


[role="lead"]
アノテーションを作成し、監視対象のアセットに割り当てる。アノテーションは、物理的な場所、終了日、ストレージ階層、ボリュームのサービスレベルなど、アセットに関する情報を提供するメモです。



== アノテーションの定義

アノテーションを使用すると、ビジネスニーズに合わせて、ビジネス固有のカスタムデータをアセットに追加できます。Cloud Insights には、アセットのライフサイクル（開始日や終了日）、建物やデータセンターの場所、階層などの一連のアノテーションがデフォルトで用意されていますが、他の方法でデータを表示することもできます。

カスタムアノテーションのデータは、スイッチのメーカー、ポートの数、パフォーマンス統計など、すでに収集されたデバイスの補足データになります。アノテーションを使用して追加したデータは Cloud Insights で検出されません。

.作業を開始する前に
* 環境のデータを関連付ける必要がある業界固有の用語をリストします。
* 環境のデータを関連付ける必要がある会社固有の用語をリストします。
* 使用できるデフォルトのアノテーションタイプがないかどうかを特定します。
* 作成する必要があるカスタムアノテーションを特定します。アセットに割り当てる前に、アノテーションを作成する必要があります。


アノテーションを作成するには、次の手順を実行します。

.手順
. Cloud Insights メニューで、 * Manage > Annotations * をクリックします
. [ * + 注釈 * （ * + Annotation * ） ] をクリックして、新しい注釈を作成する。
. 名前（ Name ）、アノテートアイテム（概要）を入力し、新しいアノテートアイテムに入力します。
+
たとえば、次のように入力して、データセンター 4 のアセットの物理的な場所を定義するテキストアノテーションを作成します。

+
** アノテーションの名前（「 Location 」など）を入力します。
** 「 Physical location is Data Center 4 」など、アノテーションの説明に使用する概要を入力します。
** アノテーションの「 type 」を入力します（「 Text 」など）。






== アセットへのアノテーションの手動割り当て

アセットにアノテーションを割り当てると、アセットをビジネスに関連付けてソート、グループ化、レポートするのに役立ちます。アノテーションルールを使用して特定のタイプのアセットにアノテーションを自動的に割り当てることができますが、アセットページを使用して個々のアセットにアノテーションを割り当てることができます。

.作業を開始する前に
* 割り当てるアノテーションを作成しておく必要があります。


.手順
. Cloud Insights 環境にログインします。
. アノテーションを適用するアセットを選択します。
+
** アセットを検索するには、クエリ、ダッシュボードウィジェットから選択、または検索します。目的のアセットが見つかったら、リンクをクリックしてアセットのランディングページを開きます。


. アセットページの [ ユーザーデータ ] セクションで、 [*+Annotation*] をクリックします。
. [ 注釈の追加 ] ダイアログボックスが表示されます。
. リストからアノテーションを選択します。
. 値をクリックし、選択したアノテーションのタイプに応じて次のいずれかを実行します。
+
** アノテーションタイプがリスト、日付、またはブーリアンの場合は、値をリストから選択します。
** アノテーションタイプがテキストの場合は、値を入力します。


. [ 保存（ Save ） ] をクリックします。


アノテーションを割り当てたあとに値を変更する場合は、アノテーションフィールドをクリックして別の値を選択します。fly_option で _Add 新規値を選択したリストタイプのアノテーションの場合は ' 既存の値を選択するだけでなく ' 新しい値を入力できます



== アノテーションルールを使用してアノテーションを割り当てる

定義した条件に基づいてアセットにアノテーションを自動的に割り当てるには、アノテーションルールを設定します。それらのルールに基づいて、アセットにアノテーションが割り当てられます。 Cloud InsightsCloud Insights には、デフォルトのアノテーションルールも 2 つ用意されています。これらのルールは、ニーズに合わせて変更することができ、不要な場合は削除することもできます。



=== アノテーションルールの作成

アノテーションを個々のアセットに手動で適用する代わりに、アノテーションルールを使用して複数のアセットに自動的にアノテーションを適用することができます。個々のアセットページで手動で設定したアノテーションは、 Insight でアノテーションルールが評価されるときにルールベースのアノテーションよりも優先されます。

.作業を開始する前に
アノテーションルールのクエリを作成しておく必要があります。

.このタスクについて
アノテーションタイプはルールの作成中に編集することもできますが、事前に定義しておくことを推奨します。

.手順
. [ 管理（ Manage ） ] > [ 注釈ルール（ Annotation rules ） ] をクリック
+
アノテーションルールページに、既存のアノテーションルールのリストが表示されます。

. 「 * + 追加」をクリックします。
. 次の手順を実行します。
+
.. [* 名前 *] ボックスに、ルールを説明する一意の名前を入力します。
+
この名前はアノテーションルールページに表示されます。

.. * クエリ * をクリックし、アセットへのアノテーションの適用に使用するクエリを選択します。
.. [* Annotation* ] をクリックし、適用する注釈を選択します。
.. * 値 * をクリックし、アノテーションの値を選択します。
+
たとえば、 Birthday のアノテーションを選択した場合は、日付の値を指定します。

.. [ 保存（ Save ） ] をクリックします。
.. すべてのルールをすぐに実行する場合は、 * すべてのルールを実行 * をクリックします。それ以外の場合、ルールは定期的に実行されます。



