---
sidebar: sidebar 
permalink: task_config_cs_data_collectors.html 
keywords: acquisition, AU, data collector, collector 
summary: データコレクタを設定する 
---
= データコレクタの設定


[role="lead"]
Cloud Insights 環境内のデータコレクタは、データセンター内のホスト、サービス、またはデバイスからデータを収集するように設定します。

.作業を開始する前に
* データコレクタを設定するには、アカウント所有者または管理者の権限が必要です。
* データの収集を開始する前に、 Acquisition Unit （インフラストラクチャの場合）または Agent （サービスまたはホストの場合）を設定しておく必要があります。
* データの収集元となるインフラデバイスのクレデンシャルが必要です。
+
データを収集するすべてのデバイスには、デバイスのネットワークアドレス、アカウント情報、およびパスワードが必要です。





=== 資格情報のセキュリティ

データコレクタのクレデンシャルは、 Cloud Insights に入力すると暗号化され、まず AU の公開鍵で暗号化された Acquisition Unit （ AU ）に送信され、 HTTPS 経由で暗号化されます。暗号化された値は、 AU がデバイスおよびソフトウェアとの通信にこれらの値を使用する場合に復号化されます。



=== Data Collector の設定

* Cloud Insights メニューで、 * Admin > Data Collector* をクリックし、 * + Data Collector* ボタンをクリックします。すべてのデータコレクタを表示することも、サブスクリプションに基づいて使用可能なデータコレクタのみを表示することもできます。


* 選択するデータコレクタのタイプによって、インストール手順は異なります。




==== オペレーティングシステム：

環境からオペレーティングシステムまたはサービスデータの収集を開始するには、少なくとも 1 つの Cloud Insights エージェントをインストールする必要があります。必要な数のエージェントをインストールできます。各エージェントは、複数のサービスからデータを収集できます。

各エージェントは、サービスからデータを収集するだけでなく、インストール先の VM / ホストのデータコレクタとしても機能します。収集されたデータは、ダッシュボードウィジェットまたはクエリでは「ノード」データとして表示されます。

. Cloud Insights にアクセスする VM またはホスト（ノード）のプラットフォームタイプまたはオペレーティングシステムをクリックします。
. エージェントアクセスキーを選択します。
. 表示されたコマンドをクリップボードにコピーします。クリップボードアイコンをクリックすると、コマンドを簡単にコピーできます。
. エージェント VM/ ホストでターミナル / コマンドウィンドウを開き、コマンドを貼り付けます。Enter キーを押してコマンドを実行します。
. エージェントをインストールしたら、 [ 完了 ] をクリックします。エージェントがデータの収集を開始します。
+
ノードのデータがダッシュボードに表示されるか、クエリに使用できるようになるまでに、最大 2 つのポーリング期間がかかることがあります。





==== サービス

サービスデータコレクタは、 Docker や Kibana などのテレグラムエージェントに基づくものです。

.作業を開始する前に
* 環境からサービスデータを収集するには、少なくとも 1 つの Cloud Insights エージェントが必要です。エージェントがインストールされていない場合は、サービスデータコレクタを設定するときに、エージェントのインストールを求めるプロンプトが表示されます。
* データの収集元となるサービスが環境にインストールされ、実行されている必要があります。
+
.. サービスデータコレクタをクリックします。
.. エージェントのオペレーティングシステムまたはプラットフォームを選択します。プラットフォーム用のエージェントをインストールしていない場合は、手順に従ってインストールしてください。
.. エージェントアクセスキーを選択します。
.. [* Continue （続行） ] をクリックします
.. データコレクタの設定手順に従います。クリップボードアイコンをクリックすると、表示されているコマンドやコードスニペットをすばやくコピーできます。
.. データコレクタが正しく設定されたら、 [* 終了 * ] をクリックします。
+
サービスのデータがダッシュボードに表示されるか、クエリに使用できるようになるまで、ポーリング期間は最大 2 回かかる場合があります。







==== インフラ

インフラストラクチャデータコレクタには、ストレージやスイッチなどがあります。

.作業を開始する前に
* インフラデータの収集を開始するためには、少なくとも 1 つの Acquisition Unit を設定しておく必要があります。
+
.. [ インフラストラクチャー ] データコレクターをクリックします。
.. データコレクタの名前を入力します。名前には次の文字を使用できます。


* 文字（ a~z ）
* 番号（ 0~9 ）
* ハイフン（ - ）
* アンダースコア (_)
* 期間（ . ）
* スペース ()
+
名前の先頭と末尾にスペース、ピリオド、ハイフンを使用することはできません。

+
.. このデータコレクタに関連付ける Acquisition Unit を入力します。
.. Configuration （設定）画面で必須フィールドを入力します。
.. [ 詳細設定 *] をクリックして、追加の設定フィールドを入力します。すべてのデータコレクタで高度な設定が必要となるわけで
.. Test Configuration* をクリックして、データコレクタが正しく設定されていることを確認します。
.. 完了したら、 [ コレクタの追加 ] をクリックします。




新しい Acquisition Unit の追加については、を参照してください link:task_configure_acquisition_unit.html["Acquisition Unit の設定"]

+ 環境のデータがダッシュボードに表示されるか、クエリに使用できるようになるまでに、最大 2 つのポーリング期間がかかる場合があります。
