---
sidebar: sidebar 
permalink: task_business_entity_annotations.html 
keywords: annotations, business entity 
summary: ビジネスエンティティのアノテーションは、ビジネス階層内のアセットの監視とレポートに使用できます 
---
= ビジネスエンティティのアノテーション
:allow-uri-read: 


[role="lead"]
アノテーションタイプ * Business Entity * を使用して、企業環境のビジネスエンティティを作成、管理します。



== ビジネスエンティティの作成

ビジネスエンティティを作成するには、次の手順を実行します。

. [ * 管理（ Manage ） ]>[ 注釈（ Annotations ） ] をクリックし、 _ ビジネスエンティティ _ リンクをクリックする。
+
現在定義されているビジネスエンティティのリストが表示されます。

. [ * + ビジネスエンティティ * （ + Business Entity * ） ] をクリック
. 「 * テナント * 」、「 * 基幹業務部門 * 」、「 * ビジネスユニット * 」、「 * プロジェクト * 」の各フィールドに値を入力します。
+
ビジネスエンティティに該当しないフィールドは、空のままにすることができます。

. 以前にフィールドに値を入力したことがある場合は、ドロップダウンからその値を選択できます。再度入力する必要はありません。



NOTE: 選択した値は、一意のビジネスエンティティを構成している必要があります。たとえば、値が _A/B/C/D_IN のビジネスエンティティがすでに存在する場合、これらの値をこの順序で別のビジネスエンティティを作成することはできません。ただし、これらの値を別の順序でビジネスエンティティを作成することは可能です。



== オブジェクトへのビジネスエンティティの適用

ビジネスエンティティをオブジェクトに適用する最も簡単な方法は、クエリを使用する方法です。

. [* クエリ（ * Queries ） ] > [ 新規クエリ（ New Query ） ] をクリックし、目的のオブジェクトタイプを選択します。フィルタを適用すると、結果をさらに絞り込むことができます。
. チェックボックスをクリックして、ビジネスエンティティを適用するオブジェクトを選択します。
. [ * 一括操作 * ] をクリックし、 [ * 注釈の追加 * ] を選択します。
. Business Entity_annotation を選択し、リストから目的のビジネスエンティティの値を選択します。
. [ 保存（ Save ） ] をクリックして、ビジネスエンティティをオブジェクトに適用する。


ビジネスエンティティを個々のオブジェクトに適用するには、オブジェクトのアセットランディングページに移動し、 User Data セクションで * + Annotation をクリックします。

を設定することもできます link:task_create_annotation_rules.html["アノテーションルール"] ビジネスエンティティをオブジェクトに適用します。


NOTE: 1 つのオブジェクトに関連付けることができるビジネスエンティティは 1 つだけです。



== オブジェクトからのビジネスエンティティの削除

オブジェクトからビジネスエンティティを削除するには、オブジェクトを照会して選択し、 * 一括処理 * をクリックして、アノテーションの削除 _ を選択します。ビジネスエンティティ注釈を選択し、 * 削除 * をクリックします。
