---
sidebar: sidebar 
permalink: task_cloud_insights_onboarding_1.html 
summary: Cloud Insights に登録して環境を作成 
---
= Cloud Insights オンボーディング


[role="lead"]
Cloud Insights の使用を開始する前に、 NetApp Cloud Central * ポータルにサインアップする必要があります。ネットアップの Cloud Central にすでにログインしている場合は、いくつかの簡単な手順で Cloud Insights の無償トライアルを開始できます。


toc::[]


== NetApp Cloud Central アカウントを作成します

ネットアップのクラウドサービスにアクセスするには、にアクセスしてください https://cloud.netapp.com["* NetApp Cloud Central *"^] [ サインアップ ] をクリックします。

* 有効なビジネス用 E メールアドレスを入力し、パスワードを選択してください。
* 会社名と氏名を入力します。
* 利用規約に同意して、 [ * サインアップ * ] をクリックします。


その後、ネットアップのクラウドサービスに関するページに移動します。

Cloud Insights を選択します。



=== すでにネットアップクラウドへのログインがある場合はどうすればよいですか？

NetApp Cloud Central アカウントをすでにお持ちの場合は、で「 * Log in * 」を選択します https://cloud.netapp.com["* NetApp Cloud Central *"^] ポータルページ。

E メールアドレスとパスワードを入力します。その後、ネットアップのクラウドサービスに関するページに移動します。

Cloud Insights を選択します。



== Cloud Insights の無償トライアルを開始しています

初めて Cloud Insights にログインする場合は、 Cloud Insights サービスの下にある無料トライアルを開始 * をクリックします。Cloud Insights が会社の環境を作成します。

環境の作成が完了したら、 Cloud Central のクレデンシャルを使用してログインし、 Cloud Insights の 30 日間の無償トライアルを開始できます。このトライアルでは、 Cloud Insights Standard Edition が提供するすべての機能を調べることができます。

無償トライアルでは、次のことが可能です link:concept_subscribing_to_cloud_insights.html["サブスクリプションを開始します"] いつでも Cloud Insights に接続できます。登録すると、現在のサブスクリプションに基づいて Cloud Insights 機能を使用できるようになります。



== サインインして実行します

テナントが作成されたら、いつでも NetApp Cloud Portal にログインして、 * Cloud Insights に移動 * をクリックできます。Cloud Insights 環境に直接移動します。

次のように、 Cloud Insights 環境の URL に直接ブラウザを開くこともできます。

 https://<environment-name>.c01.cloudinsights.netapp.com/
また、 URL は各ユーザーの招待メールにも含まれ、簡単にアクセスしたりブックマークを付けたりできます。ユーザがまだ Cloud Central にログインしていない場合は、ログインするように求められます。


NOTE: 新しいユーザは、 Cloud Central にアクセスして環境の URL にアクセスする前に、まだサインアップしている必要があります。

新しい環境に初めてログインするときは、のセットアップ手順が表示されます link:task_getting_started_with_cloud_insights.html["* データの収集を開始 *"]。



== ログアウトしています

Cloud Insights からログアウトするには、 * ユーザー名 * をクリックし、 * ログアウト * を選択します。Cloud Central のサインイン画面に戻ります。


NOTE: Cloud Insights からログアウトすると、 Cloud Central からログアウトされます。また、 Cloud Central サインインを使用する他の NetApp クラウドサービスからもログアウトされます。
